/**
 * Maker Studio（编辑器本体）汉化字典
 *
 * 说明：Maker Studio 编辑器本体（应用界面）的简体中文翻译。
 * 已从 index.js 中拆出，避免主文件过于臃肿。
 *
 * 键 = 应用的英文源字符串（gettext 风格，必须与源码完全一致，区分大小写）。
 * 占位符如 {file} / {count} / {n} 需原样保留在翻译里，运行时由编辑器替换。
 *
 * index.js 通过 `import { makerStudioDict } from "./maker-studio.js"` 引入，
 * 与 pbs-editor.js 的字典一起合并进 zh-CN locale。
 */
export const makerStudioDict = {
  // ── Menu bar ──────────────────────────────────────────────────────────────
  "File": "文件",
  "Open Project...": "打开项目…",
  "Open Recent": "打开最近项目",
  "No recent projects": "没有最近的项目",
  "Clear Recent Projects": "清除最近项目",
  "Save All": "全部保存",
  "Create Project File…": "创建项目文件…",
  "Project file created. Double-click it in your file manager to open the project.": "项目文件已创建。在文件管理器中双击它即可打开项目。",
  "A .makerstudio file already exists in this project folder. Overwrite?": "此项目文件夹中已存在 .makerstudio 文件。是否覆盖？",
  "Run Game": "运行游戏",
  "Open Project Folder": "打开项目文件夹",
  "Open Saves Folder": "打开存档文件夹",
  "Clear Proton Preference": "清除 Proton 偏好",
  "More": "更多",

  "Edit": "编辑",
  "Undo": "撤销",
  "Redo": "重做",
  "Cut": "剪切",
  "Copy": "复制",
  "Paste": "粘贴",
  "Advanced Clipboard": "高级剪贴板",
  "Copy All Layers": "复制所有图层",
  "Cut All Layers": "剪切所有图层",
  "Paste to Original Layers": "粘贴到原图层",
  "Cross-Project Clipboard": "跨项目剪贴板",
  "Select All": "全选",
  "Deselect": "取消选择",
  "Shadows": "阴影",
  "Generate from Selection": "从选择生成",
  "Delete All Shadows": "删除所有阴影",

  "View": "视图",
  "Panels": "面板",
  "Maps": "地图",
  "Tile Palette": "图块面板",
  "Scroll to the selected tile": "滚动到选中的图块",
  "(graphic not found)": "（未找到图形）",
  "Layers": "图层",
  "Tile Properties": "图块属性",
  "Tile Info": "图块信息",
  "Events": "事件",
  "Minimap": "小地图",
  "Show Grid": "显示网格",
  "Show Collision": "显示碰撞",
  "Show Events": "显示事件",
  "Show Event Cells": "显示事件格",
  "Create Events on Double-Click": "双击创建事件",
  "Dim Inactive Layers": "淡化非活动图层",
  "Show MS-Exclusive Indicators": "显示MS专属功能指示器",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "Zoom 100%": "缩放至100%",
  "Dark Mode": "深色模式",
  "Language": "语言",
  "Layout": "布局",
  "Refresh Layout": "重置布局",
  "Import Configuration...": "导入配置…",
  "Export Configuration...": "导出配置…",

  "Map": "地图",
  "New Map...": "新建地图…",
  "Duplicate Map": "复制地图",
  "Map Versions...": "地图版本…",
  "Resize / Shift Map...": "调整大小 / 平移地图…",
  "Change Tileset...": "更换图块集…",
  "Change Battleback...": "更换战斗背景…",
  "Map Audio...": "地图音频…",
  "Map Audio…": "地图音频…",
  "Map Audio": "地图音频",
  "Auto-Change BGM": "自动更换 BGM",
  "Auto-Change BGS": "自动更换 BGS",
  "Failed to save map audio: {error}": "保存地图音频失败：{error}",
  "Import Map from JSON...": "从 JSON 导入地图…",
  "Export Map": "导出地图",
  "Export as JSON...": "导出为 JSON…",
  "Export as PNG...": "导出为 PNG…",
  "Export as GIF (animated)...": "导出为 GIF（动画）…",
  "Export as WebP (animated)...": "导出为 WebP（动画）…",

  "Tools": "工具",
  "Brush": "画笔",
  "Eraser": "橡皮擦",
  "Fill": "填充",
  "Rectangle": "矩形",
  "Eyedropper": "吸取",
  "Select": "选择",
  "Pan": "平移",
  "Rotate CW": "顺时针旋转",
  "Rotate CCW": "逆时针旋转",
  "Flip Horizontal": "水平翻转",
  "Flip Vertical": "垂直翻转",
  "Database...": "数据库…",
  "Scripts...": "脚本…",

  "Mods": "模组",
  "Mod Manager": "模组管理器",

  "Help": "帮助",
  "Documentation": "文档",
  "Keyboard Shortcuts...": "键盘快捷键…",
  "Check for Updates...": "检查更新…",
  "Stats...": "统计…",
  "About Maker Studio": "关于 Maker Studio",
  "Toggle DevTools": "切换开发者工具",
  "Install Linux File Association…": "安装 Linux 文件关联…",
  "Installed: {file}": "已安装：{file}",
  "MIME: {file}": "MIME：{file}",

  // ── Session / autosave toasts ────────────────────────────────────────────
  "This project appears to be open in another Maker Studio window. Editing it in both can silently lose changes — the last save wins.": "此项目似乎已在另一个 Maker Studio 窗口中打开。在两个窗口中编辑可能会静默丢失更改——后保存的会覆盖先保存的。",
  "Autosaved changes from a previous session found for {maps}. Restore writes them to the map files (the previous state stays in Data/map-backups).": "为 {maps} 找到了之前会话的自动保存更改。恢复会将其写入地图文件（之前的状态保留在 Data/map-backups 中）。",
  "Restore": "恢复",
  "map {ids}": "地图 {ids}",
  "maps {ids}": "地图 {ids}",
  "Restore failed for map {id}: {error}": "恢复地图 {id} 失败：{error}",
  "Restored autosaved changes for {count} map(s).": "已恢复 {count} 个地图的自动保存更改。",

  // ── Toolbar ──────────────────────────────────────────────────────────────
  "Save ({key}) · Shift+Click: Save All ({allKey})": "保存 ({key}) · Shift+点击：全部保存 ({allKey})",
  "Run Game ({key}) — Shift+Click to choose the Proton prefix": "运行游戏 ({key}) — Shift+点击可选择 Proton 前缀",
  "Run": "运行",
  "Game is already launching…": "游戏正在启动…",
  "No game project loaded.": "未加载游戏项目。",
  "Game launched": "游戏已启动",
  "Failed to launch game: {error}": "启动游戏失败：{error}",
  "Could not get Proton options: {error}": "无法获取 Proton 选项：{error}",
  "Could not initialize Proton prefix: {error}": "无法初始化 Proton 前缀：{error}",
  "The game is already running with this Proton prefix.": "游戏已在使用此 Proton 前缀运行。",
  "Game is already running.": "游戏已在运行。",
  "Game is already running — brought to front.": "游戏已在运行——已置前。",

  // ── Already-running dialog ────────────────────────────────────────────────
  "Game already running": "游戏已在运行",
  "The game is already open. Do you want to launch another instance?": "游戏已打开。是否要启动另一个实例？",
  "The game is already open. Proton cannot run two instances at once — close it and reopen to apply your changes.": "游戏已打开。Proton 无法同时运行两个实例——请关闭并重新打开以应用更改。",
  "Open Anyway": "仍然打开",
  "Bring to Front": "置前",
  "Close and Reopen": "关闭并重新打开",
  "Game restarted": "游戏已重启",

  // ── Proton prefix dialog ───────────────────────────────────────────────────
  "Select Proton environment": "选择 Proton 环境",
  "Select how to run the game": "选择如何运行游戏",
  "Choose how you want to launch the game on Linux.": "选择你希望如何在 Linux 上启动游戏。",
  "Which option do you want to use?": "你想使用哪个选项？",
  "Run native Linux build": "运行 Linux 原生版本",
  "Uses Game_Linux in the project folder (mkxp-z native build)": "使用项目文件夹中的 Game_Linux（mkxp-z 原生构建）",
  "Detected the Proton prefix for": "检测到以下游戏的 Proton 前缀",
  "on Steam. The most reliable option for games with the RTP installed.": "在 Steam 上。对于安装了 RTP 的游戏来说是最可靠的选项。",
  "Which prefix do you want to use to run the game?": "你想用哪个前缀来运行游戏？",
  "Use RPG Maker XP prefix": "使用 RPG Maker XP 前缀",
  "Recommended — includes RTP and Windows registry (App ID {appId})": "推荐——包含 RTP 和 Windows 注册表（App ID {appId}）",
  "Use configured prefix": "使用已配置的前缀",
  "App ID: {appId}": "App ID：{appId}",
  "Use Maker Studio prefix": "使用 Maker Studio 前缀",
  "Own prefix already configured": "已配置自己的前缀",
  "A new prefix will be created (first time only, may take a few minutes)": "将创建新前缀（仅首次，可能需要几分钟）",
  "Remember my choice for this project": "记住我对这个项目的选择",
  "Preparing Windows environment for the first time…": "正在首次准备 Windows 环境…",
  "This may take between 30 seconds and 2 minutes.": "这可能需要 30 秒到 2 分钟。",

  "Saves": "存档",
  "Open the Wine/Proton prefix AppData\\Roaming (saved games)": "打开 Wine/Proton 前缀的 AppData\\Roaming（存档）",
  "Open saved-games folder (%AppData%\\<Game>)": "打开存档文件夹（%AppData%\\<Game>）",
  "Open Game Simulator for current map": "为当前地图打开游戏模拟器",
  "Sim Map": "模拟地图",
  "{tool} — disabled on the Events layer": "{tool}——在事件图层上已禁用",
  "Size": "大小",
  "Brush size doesn't apply on the Events layer": "画笔大小不适用于事件图层",
  "Eraser size doesn't apply on the Events layer": "橡皮擦大小不适用于事件图层",
  "Continuous": "连续",
  "Zoom": "缩放",
  "Open the Database (Tilesets, Switches, Variables, Animations, Common Events)": "打开数据库（图块集、开关、变量、动画、公共事件）",
  "Database": "数据库",
  "Open the Scripts editor (view / reorder / edit Scripts.rxdata)": "打开脚本编辑器（查看 / 排序 / 编辑 Scripts.rxdata）",
  "Scripts": "脚本",
  "Manage map versions (create / switch / duplicate / set selector / delete)": "管理地图版本（创建 / 切换 / 复制 / 设置选择器 / 删除）",
  "Versions": "版本",
  "Grid": "网格",
  "Collision": "碰撞",
  "Col": "碰撞",
  "Dim Layers": "淡化图层",
  "Dim": "淡化",
  "Switch to Light Mode": "切换到浅色模式",
  "Switch to Dark Mode": "切换到深色模式",
  "Saved-games folder not found.": "未找到存档文件夹。",
  "Could not open the saved-games folder: {error}": "无法打开存档文件夹：{error}",
  "No Wine/Proton prefix found.": "未找到 Wine/Proton 前缀。",
  "Could not open the folder: {error}": "无法打开文件夹：{error}",

  // ── Status bar ───────────────────────────────────────────────────────────
  "Tool": "工具",
  "Layer {n}": "图层 {n}",
  "Tile": "图块",
  "Event": "事件",
  "Rendering": "渲染中",
  "Encoding…": "编码中…",
  "Writing…": "写入中…",
  "Animations paused (performance)": "动画已暂停（性能）",
  "Map animations (autotiles, fog) are paused because rendering can't keep up. They resume automatically when performance recovers.": "地图动画（自动图块、迷雾）已暂停，因为渲染跟不上。性能恢复后会自动继续。",

  // ── Tabs & dock panels ───────────────────────────────────────────────────
  "Close tab": "关闭标签页",
  "Close": "关闭",
  "Close panel": "关闭面板",

  // ── Layer panel ──────────────────────────────────────────────────────────
  "Rename": "重命名",
  "Hide Layer": "隐藏图层",
  "Show Layer": "显示图层",
  "Duplicate Layer": "复制图层",
  "Delete Layer": "删除图层",
  "Delete layer \"{name}\" and everything painted on it?": "删除图层 \"{name}\" 及其上绘制的一切？",
  "Edit…": "编辑…",
  "Delete Event": "删除事件",
  "Confirm": "确认",
  "Add extended layer": "添加扩展图层",
  "Click to enter events mode (RPG Maker XP–style)": "点击进入事件模式（RPG Maker XP 风格）",
  "Hide events": "隐藏事件",
  "Show events": "显示事件",
  "Collapse": "折叠",
  "Expand": "展开",
  "Hide": "隐藏",
  "Show": "显示",
  "Shadows require the MakerStudio plugin in-game": "阴影需要游戏中的 MakerStudio 插件",
  "Shadow {n}": "阴影 {n}",
  "Hover for outline • Drag to reorder • Right-click for actions": "悬停查看轮廓 • 拖拽以重新排序 • 右键打开操作菜单",
  "Edit shadow config": "编辑阴影配置",
  "Delete shadow": "删除阴影",
  "Add fog": "添加迷雾",
  "Add panorama": "添加全景图",
  "Add layer": "添加图层",
  "Edit fog config": "编辑迷雾配置",
  "Edit panorama config": "编辑全景图配置",
  "Edit layer config": "编辑图层配置",
  "Delete fog": "删除迷雾",
  "Delete panorama": "删除全景图",
  "Delete layer": "删除图层",
  "Multiple fog layers require the MakerStudio plugin in-game": "多个迷雾图层需要游戏中的 MakerStudio 插件",
  "Multiple panorama layers require the MakerStudio plugin in-game": "多个全景图图层需要游戏中的 MakerStudio 插件",
  "Custom layer group (priority {priority}) — requires the MakerStudio plugin in-game": "自定义图层组（优先级 {priority}）——需要游戏中的 MakerStudio 插件",
  "Click to select": "点击以选择",
  "native": "原生",
  "Extended layers beyond RPG Maker XP's 3 require the MakerStudio plugin in-game": "超过 RPG Maker XP 的 3 层扩展图层需要游戏中的 MakerStudio 插件",
  "Opacity: {value}": "不透明度：{value}",
  "Remove layer": "移除图层",
  "Fog": "迷雾",
  "Panorama": "全景图",

  // ── Events panel ─────────────────────────────────────────────────────────
  "New event": "新建事件",
  "Delete selected event": "删除选中事件",
  "Double-click to edit. Delete to remove.": "双击以编辑。按 Delete 以删除。",
  "(unnamed)": "（未命名）",
  "Edit...": "编辑…",
  "Delete event {id}?": "删除事件 {id}？",
  "Position": "位置",
  "Pages": "页",
  "Page {n}": "第 {n} 页",
  "Action Button": "行动键",
  "Player Touch": "玩家接触",
  "Event Touch": "事件接触",
  "Autorun": "自动执行",
  "Parallel Process": "并行处理",

  // ── Tile palette ─────────────────────────────────────────────────────────
  "{name} (map default)": "{name}（地图默认）",
  "Autotile: {name}": "自动图块：{name}",
  "Open Autotile": "打开自动图块",
  "Edit Properties...": "编辑属性…",
  "Edit Tileset...": "编辑图块集…",
  "Delete the selected tileset": "删除选中的图块集",
  "Edit Name/Graphic...": "编辑名称/图形…",
  "Search tilesets…": "搜索图块集…",
  "Tiles painted from another tileset require the MakerStudio plugin in-game": "使用其他图块集绘制的图块需要游戏中的 MakerStudio 插件",
  "No tilesets match.": "没有匹配的图块集。",
  "Autotiles use Maker Studio's own autotile system — requires the MakerStudio plugin in-game": "自动图块使用 Maker Studio 自己的自动图块系统——需要游戏中的 MakerStudio 插件",
  "Search autotiles…": "搜索自动图块…",
  "Clear search": "清除搜索",
  "No autotiles match.": "没有匹配的自动图块。",
  "No autotiles found.": "未找到自动图块。",

  // ── Properties panel (Tile Info) ─────────────────────────────────────────
  "Type": "属性",
  "Extra Autotile": "额外自动图块",
  "Pattern": "图案",
  "Passable": "可通行？",
  "0 (Below)": "0（下方）",
  "{priority} (Above)": "{priority}（上方）",
  "Terrain": "地形",
  "Unknown": "未知",
  "Bush": "灌木",
  "Counter": "柜台",
  "Empty": "空",
  "Autotile {n} (pattern {pattern})": "自动图块 {n}（图案 {pattern}）",
  "Tileset tile {n}": "图块{n}",
  "Tileset {id}": "图块集 {id}",
  "Default": "默认",
  "Tile ID": "图块 ID",
  "Tileset": "图块集",

  // ── Map tree ─────────────────────────────────────────────────────────────
  "Create a new blank map": "创建新的空白地图",
  "New Map Here...": "在此新建地图…",
  "Search maps...": "搜索地图…",
  "No maps loaded": "未加载地图",
  "Delete Map": "删除地图",
  "Delete map \"{name}\" and reparent {count} child map(s) to its parent?\nThis deletes {file} permanently.": "删除地图 \"{name}\" 并将 {count} 个子地图重新挂到其父级？\n这将永久删除 {file}。",
  "Delete map \"{name}\"?\nThis deletes {file} permanently.": "删除地图 \"{name}\"？\n这将永久删除 {file}。",
  "Delete failed: {error}": "删除失败：{error}",
  "Move failed: {error}": "移动失败：{error}",
  "Duplicate failed: {error}": "复制失败：{error}",
  "Open Map": "打开地图",
  "Version {n}: {name}": "版本 {n}：{name}",
  "Version 1 (Base)": "版本 1（基础）",
  "Version {n}": "版本 {n}",
  "New Version…": "新版本…",
  "Set Selector…": "设置选择器…",
  "Rename Version…": "重命名版本…",
  "Delete Version": "删除版本",
  "Change Battleback (this version)…": "更换战斗背景（此版本）…",
  "Manage Versions…": "管理版本…",
  "Versions ({count}) — on Version {n}…": "版本（{count}）——位于版本 {n}…",
  "Versions…": "版本…",
  "Rename Version": "重命名版本",
  "Rename Version {n}.": "重命名版本 {n}。",
  "Version name": "版本名称",
  "Delete \"{name}\" (Version {n})?\nThis removes the version's tiles and events from the map. It cannot be undone.": "删除 \"{name}\"（版本 {n}）？\n这将从地图中移除该版本的图块和事件。此操作无法撤销。",
  "Open map failed": "打开地图失败",
  "Switch version failed": "切换版本失败",
  "Create version failed": "创建版本失败",
  "Delete version failed": "删除版本失败",
  "Update version failed": "更新版本失败",
  "Edit Event": "编辑事件",
  "Delete Selection": "删除选择",
  "Fill With Selected Tile": "用选中的图块填充",
  "Set as Player Start": "设为玩家起点",
  "Player start set to ({x}, {y})": "玩家起点已设为 ({x}, {y})",
  "Failed to set player start: {error}": "设置玩家起点失败：{error}",
  "Tile already has an event": "此图块上已有事件",
  "Move would leave the map": "移动会超出地图范围",
  "Change Tileset…": "更换图块集…",
  "Change Battleback…": "更换战斗背景…",
  "Resize / Shift Map…": "调整大小 / 平移地图…",
  "Export Map…": "导出地图…",
  "Export as JSON…": "导出为 JSON…",
  "Export as PNG…": "导出为 PNG…",
  "Export as GIF (animated)…": "导出为 GIF（动画）…",
  "Export as WebP (animated)…": "导出为 WebP（动画）…",
  "Export JSON": "导出 JSON",
  "Export PNG": "导出 PNG",
  "Export GIF": "导出 GIF",
  "Export WebP": "导出 WebP",
  "Map JSON": "地图 JSON",
  "Map PNG": "地图 PNG",
  "Map GIF": "地图 GIF",
  "Map WebP": "地图 WebP",
  "Map JSON export": "导出地图 JSON",
  "PNG export": "导出 PNG",
  "GIF export": "导出 GIF",
  "WebP export": "导出 WebP",
  "Include Events?": "包含事件？",
  "Render event sprites onto the exported image?\nEach event is drawn using its active page's character graphic.": "在导出的图像上渲染事件精灵图？\n每个事件都使用其活动页的角色图形绘制。",
  "Include events": "包含事件",
  "No events": "无事件",
  "Loop forever?": "无限循环？",
  "Play the animation in an infinite loop, or play it once?": "以无限循环播放动画，还是只播放一次？",
  "Infinite loop": "无限循环",
  "Play once": "播放一次",
  "{label} saved: {file}": "{label} 已保存：{file}",
  "{label} failed: {error}": "{label} 失败：{error}",
  "Open folder": "打开文件夹",
  "Delete Map…": "删除地图…",
  "This map has {total} versions (Base + {extra}). Currently editing Version {active}. Right-click → Versions to manage.": "此地图有 {total} 个版本（基础 + {extra}）。当前正在编辑版本 {active}。右键 → 版本进行管理。",

  // ── Mod manager panel ────────────────────────────────────────────────────
  "Rescan": "重新扫描",
  "Project Mods": "项目模组",
  "Global Mods": "全局模组",
  "No mods found.": "未找到模组。",
  "blocked": "已阻止",
  "Update": "更新",
  "Reload": "重新加载",
  "Disable": "禁用",
  "Enable": "启用",
  "Uninstall": "卸载",
  "authors:": "作者：",
  "id:": "id：",
  "source:": "来源：",
  "plugin deps:": "插件依赖：",
  "folder:": "文件夹：",
  "Logs": "日志",
  "Clear": "清除",
  "No log entries.": "没有日志条目。",
  "Mod loaded but logged errors at runtime — expand to see the logs.": "模组已加载但在运行时记录了错误——展开以查看日志。",
  "runtime errors": "运行时错误",
  "load error": "加载错误",
  "active": "活动",
  "disabled": "已禁用",
  "+{count} more": "另有 +{count} 个",

  // ── Game Simulator ───────────────────────────────────────────────────────
  "Game Simulator — Map {id}": "游戏模拟器——地图 {id}",
  "Game Simulator — Event {id} page {page}": "游戏模拟器——事件 {id} 第 {page} 页",
  "Game Simulator — Test Move Route on {target}": "游戏模拟器——在 {target} 上测试移动路线",
  "Player": "玩家",
  "This Event ({id})": "此事件（{id}）",
  "Event {id}": "事件 {id}",
  "Player:": "玩家：",
  "walk": "行走",
  "action": "行动",
  "cancel": "取消",
  "View only:": "仅查看：",
  "Player input disabled": "玩家输入已禁用",
  "Camera:": "镜头：",
  "Drag/Scroll = pan": "拖拽/滚动 = 移动",
  "toggle fixed/free": "切换镜头固定/自由",
  "Right-click:": "右键：",
  "Set player position here": "在此设置玩家位置",
  "Sim:": "模拟：",
  "play/pause": "播放/暂停",
  "step": "单步",
  "restart": "重启",
  "close": "关闭",
  "Event Log": "事件日志",
  "Play": "播放",
  "Pause": "暂停",
  "Step one frame": "运行一帧",
  "Step": "运行单帧",
  "Restart": "重启",
  "Auto-restart when interpreters finish": "解释器完成后自动重启",
  "Loop": "循环",
  "Camera mode ({key}). Fixed = follows player/event. Free = drag/scroll to pan.": "镜头模式（{key}）。固定 = 跟随玩家/事件。自由 = 拖拽/滚动以平移。",
  "Fixed Camera": "固定镜头",
  "Free Camera": "自由镜头",
  "Speed": "速度",
  "Player start, canvas size, etc.": "玩家起点、画布大小等。",
  "Settings": "设置",
  "playing": "播放中",
  "paused": "已暂停",
  "Frame": "帧",
  "Cam": "镜头",
  "Interp": "解释器",
  "Simulator Settings": "模拟器设置",
  "Canvas Size": "画布大小",
  "(persisted per project)": "（按项目保存）",
  "Frame Rate": "帧率",
  "Max FPS": "最大 FPS",
  "The game's own frame rate (mkxp `fixedFramerate`, 60 by default). Sets the sim's tick rate; walking speed and every 1/20 s duration (Wait, Screen Shake) scale with it so they keep their wall-clock timing.": "调整游戏的帧率（mkxp `fixedFramerate`，默认60帧）会改变游戏内部逻辑的运行速度，但行走速度、等待时长、屏幕震动等效果会自动按比例缩放，确保它们在现实世界中的持续时间不变。",
  "Width": "宽度",
  "Height": "高度",
  "Preset": "预设",
  "— pick —": "— 选择 —",
  "Player Start": "玩家起点",
  "(map {id})": "（地图 {id}）",
  "Player X": "玩家 X",
  "Player Y": "玩家 Y",
  "Direction": "方向",
  "Down": "下",
  "Left": "左",
  "Right": "右",
  "Up": "上",
  "Character": "角色",
  "(none — fallback marker)": "（未选用）",
  "Player start changes apply on next Restart. Canvas size applies immediately.": "玩家起点的更改在下次重启时生效。画布大小立即生效。",
  "Apply & Restart": "应用并重启",

  // ── Common dialog buttons ────────────────────────────────────────────────
  "OK": "确定",
  "Cancel": "取消",
  "Create": "创建",
  "Apply": "应用",
  "Parent": "父级",
  "(root)": "（根）",

  // ── New Map dialog ───────────────────────────────────────────────────────
  "New Map": "新建地图",
  "Search by name or ID...": "按名称或 ID 搜索…",
  "No project loaded.": "未加载项目。",
  "Width/height must be 1..999.": "宽/高必须在 1..999 之间。",
  "Invalid tileset.": "图块集无效。",
  "Failed to create map: {error}": "创建地图失败：{error}",

  // ── Close / unsaved-changes dialogs ──────────────────────────────────────
  "has unsaved changes.": "有未保存的更改。",
  "What would you like to do?": "你想怎么做？",
  "Save & Close": "保存并关闭",
  "Unsaved Maps": "未保存的地图",
  "The following maps have unsaved changes:": "以下地图有未保存的更改：",
  "What would you like to do before exiting?": "退出前你想怎么做？",
  "Saving...": "保存中…",
  "Save All & Exit": "全部保存并退出",

  // ── Resize Map dialog ────────────────────────────────────────────────────
  "Resize Map": "调整地图大小",
  "Width/height must be > 0": "宽/高必须 > 0",
  "Large map ({w}x{h}). Continue?": "大地图（{w}x{h}）。继续？",
  "{count} tile(s) will be dropped. Continue?": "将丢弃 {count} 个图块。继续？",
  "Anchor": "锚点",
  "Wrap": "补位",
  "Reset": "重置",
  "New": "新",
  "Old": "旧",
  "{kept}/{total} kept": "保留 {kept}/{total}",
  "{count} wrap": "补位{count}",
  "{count} drop": "丢弃{count}",
  "Ctrl+Z restores the original size.": "Ctrl+Z 恢复原始大小。",

  // ── About / Update / Open-Link dialogs ───────────────────────────────────
  "About": "关于",
  "A modern, feature-rich tile map editor for Pokémon Essentials — a full replacement for RPG Maker XP.": "适用于 Pokémon Essentials 的现代化、功能丰富的图块地图编辑器——RPG Maker XP 的完全替代品。",
  "Made by": "制作",
  "Special Thanks": "特别感谢",
  "Made better by everyone who tested, contributed, and believed in the project.": "感谢所有测试、贡献并相信这个项目的人。",
  "Testing": "测试",
  "Development": "开发",
  "Other contributions": "其他贡献",
  "Up to Date": "已是最新",
  "Update Available": "有可用更新",
  "Maker Studio is up to date.": "Maker Studio 已是最新。",
  "Maker Studio v{version} is available": "Maker Studio v{version} 可用",
  "Released: {date}": "发布于：{date}",
  "Update installed! Restarting...": "更新已安装！正在重启…",
  "Download & Install": "下载并安装",
  "Later": "稍后",
  "Retry": "重试",

  // ── Game integration (Plugins/MakerStudio) ───────────────────────────────
  "Check Game Integration...": "检查游戏集成…",
  "Game Integration": "游戏集成",
  "Integration Up to Date": "集成已是最新",
  "This project's integration is up to date (v{version}).": "此项目的集成已是最新（v{version}）。",
  "This project's integration is v{version} — older than the editor.": "此项目的集成是 v{version}——比编辑器旧。",
  "This project's integration predates version stamping.": "此项目的集成早于版本标记功能。",
  "To enjoy everything Maker Studio adds, make sure the integration is installed in your game.": "要享受 Maker Studio 添加的所有功能，请确保你的游戏中安装了集成。",
  "Without it the editor still works, but your game ignores extended layers, shadows, extra autotiles and per-tile effects. Pick the build that matches your project and it installs itself.": "没有它编辑器仍可工作，但你的游戏会忽略扩展图层、阴影、额外自动图块和逐图块效果。选择与你的项目匹配的版本，它会自动安装。",
  "Build:": "版本：",
  "This build can't auto-install: it pastes into the Script Editor. Download grabs the zip — then paste the .rb inside it into a script slot.": "此版本无法自动安装：需要粘贴到脚本编辑器中。下载获取 zip——然后把其中的 .rb 粘贴到一个脚本栏位。",
  "Zip downloaded. Open the folder and paste the .rb into the Script Editor.": "zip 已下载。打开文件夹并将 .rb 粘贴到脚本编辑器中。",
  "Download": "下载",
  "Open Folder": "打开文件夹",
  "Integration installed. Restart the game for it to take effect.": "集成已安装。重启游戏以使其生效。",
  "Get the Integration": "获取集成",
  "Updating replaces the pasted Maker Studio script in place. No other script is touched, and the script bank is backed up first.": "更新会就地替换已粘贴的 Maker Studio 脚本。不会触碰其他脚本，且会先备份脚本库。",
  "Build: {build}": "版本：{build}",
  "Build: {build} (detected)": "版本：{build}（检测到）",
  "This integration doesn't match any known build, so it can't be updated automatically.": "此集成与任何已知版本都不匹配，因此无法自动更新。",
  "Updating replaces the plugin files. 003_Editor/ (your mods and portable editor) is kept.": "更新会替换插件文件。003_Editor/（你的模组和便携式编辑器）会保留。",
  "Downloading and installing…": "正在下载并安装…",
  "Integration updated. Restart the game for it to take effect.": "集成已更新。重启游戏以使其生效。",
  "Update Now": "立即更新",
  "Download Manually": "手动下载",
  "Open External Link": "打开外部链接",
  "This link will open in your default browser. Only open links you trust.": "此链接将在你的默认浏览器中打开。只打开你信任的链接。",
  "Open Link": "打开链接",

  // ── Stats dialog ─────────────────────────────────────────────────────────
  "Stats": "统计",
  "{m}m": "{m}分",
  "{h}h {m}m": "{h}时 {m}分",
  "Highlights": "亮点",
  "Most edited map by tile changes": "按图块更改计算编辑最多的地图",
  "Most Edited Map": "编辑最多的地图",
  "({count} edits)": "（{count} 次编辑）",
  "Custom": "自定义",
  "Project": "项目",
  "Global": "全局",
  "Time Spent": "花费时间",
  "Active editing time on this project": "在此项目上的有效编辑时间",
  "Tiles Placed": "放置的图块",
  "Total tiles placed on this project": "在此项目上放置的图块总数",
  "Undos": "撤销",
  "Undo operations on this project": "在此项目上的撤销操作",
  "Redos": "重做",
  "Redo operations on this project": "在此项目上的重做操作",
  "Maps Created": "创建的地图",
  "New maps created in this project": "在此项目中创建的新地图",
  "Maps Saved": "保存的地图",
  "Map saves in this project": "在此项目中的地图保存次数",
  "Sessions": "会话",
  "Times this project was opened": "此项目的打开次数",
  "First Opened": "首次打开",
  "When this project was first opened": "此项目的首次打开时间",
  "Total Time": "总时间",
  "Active editing time across all projects": "所有项目上的有效编辑时间",
  "Total Tiles Placed": "放置的图块总数",
  "Tiles placed across all projects": "所有项目上放置的图块",
  "Total Undos": "撤销总数",
  "Undo operations across all projects": "所有项目上的撤销操作",
  "Total Redos": "重做总数",
  "Redo operations across all projects": "所有项目上的重做操作",
  "Total Maps Created": "创建的地图总数",
  "Maps created across all projects": "所有项目中创建的地图",
  "Total Maps Saved": "保存的地图总数",
  "Map saves across all projects": "所有项目中的地图保存次数",
  "Total Sessions": "会话总数",
  "Total editor sessions": "编辑器会话总数",
  "Editor Since": "编辑器起始时间",
  "When the editor was first launched": "编辑器首次启动的时间",

  // ── Plugin warning + unsaved-changes prompt ──────────────────────────────
  "This project does not have a Plugins folder (Essentials v16 / BES). Plugin dependencies cannot be verified.": "此项目没有 Plugins 文件夹（Essentials v16 / BES）。无法验证插件依赖。",
  "Plugin \"{name}\" is not installed.": "插件 \"{name}\" 未安装。",
  "Plugin \"{name}\" version mismatch.": "插件 \"{name}\" 版本不匹配。",
  "Plugin Warning — {mod}": "插件警告——{mod}",
  "depends on plugin": "依赖插件",
  "Don't show this warning again": "不再显示此警告",
  "You have unsaved changes. What would you like to do?": "你有未保存的更改。你想怎么做？",

  // ── Switch / Variable picker ─────────────────────────────────────────────
  "Switch": "开关",
  "Variable": "变量",
  "Change Maximum": "更改最大值",
  "Change Maximum…": "更改最大值…",
  "Number of switches:": "开关数量：",
  "Number of variables:": "变量数量：",
  "Search switches...": "搜索开关…",
  "Search variables...": "搜索变量…",
  "+ Add {count} more": "+ 再添加 {count} 个",
  "Set how many entries exist (add or remove)": "设置存在多少个条目（添加或移除）",

  // ── Entity selector + RPG record kinds ───────────────────────────────────
  "Select {label}": "选择 {label}",
  "Search {label}...": "搜索 {label}…",
  "No {label} defined.": "未定义 {label}。",
  "Actor": "角色",
  "Class": "职业",
  "Skill": "技能",
  "Weapon": "武器",
  "Armor": "防具",
  "Enemy": "敌人",
  "Troop": "敌群",
  "State": "状态",
  "Animation": "动画",
  "Common Event": "公共事件",

  // ── Map / Event / Tileset selectors ──────────────────────────────────────
  "Select Map": "选择地图",
  "No maps in project.": "项目中没有地图。",
  "Select Event": "选择事件",
  "Search events...": "搜索事件…",
  "No events on this map.": "此地图上没有事件。",
  "Select Tileset": "选择图块集",
  "No tilesets defined.": "未定义图块集。",

  // ── Audio selector ───────────────────────────────────────────────────────
  "Audio — {category}": "音频——{category}",
  "(None)": "（无）",
  "Search…": "搜索…",
  "Browse for an audio file": "浏览音频文件",
  "Volume": "音量",
  "Pitch": "音调",
  "Stop": "停止",

  // ── Keyboard button selector ─────────────────────────────────────────────
  "Select Button": "选择按钮",
  "Code {code}": "代码 {code}",

  // ── Tileset picker ───────────────────────────────────────────────────────
  "Edit Tileset Properties — Pick": "编辑图块集属性——选择",
  "Change tileset from {from} to {to}?\n\nWarning: this does not remap tile IDs. Existing tiles may display incorrectly.": "将图块集从 {from} 更改为 {to}？\n\n警告：这不会重新映射图块 ID。现有图块可能显示不正确。",
  "Failed to change tileset: {error}": "更换图块集失败：{error}",
  "(current)": "（当前）",
  "Edit Properties…": "编辑属性…",

  // ── Tile properties editor ───────────────────────────────────────────────
  "Per-tile opacity/rotation/hue/flip effects require the MakerStudio plugin in-game": "逐图块的不透明度/旋转/色调/翻转效果需要游戏中的 MakerStudio 插件",
  "Locked: properties persist when selecting another tile": "已锁定：选择另一个图块时属性保持不变",
  "Unlocked: properties reset when selecting another tile": "未锁定：选择另一个图块时属性会重置",
  "Manage presets": "管理预设",
  "Presets…": "预设…",
  "Hue:": "色调：",
  "Saturation:": "饱和度：",
  "Lighting:": "亮度：",
  "Opacity:": "不透明度：",
  "Transform:": "变换：",
  "Rotate 90° counter-clockwise": "逆时针旋转 90°",
  "Rotate counter-clockwise": "逆时针旋转",
  "Rotate 90° clockwise": "顺时针旋转 90°",
  "Rotate clockwise": "顺时针旋转",
  "Flip horizontal": "水平翻转",
  "Flip vertical": "垂直翻转",
  "Autotiles cannot be rotated or flipped — their pattern depends on the surrounding tiles": "自动图块无法旋转或翻转——它们的图案取决于周围的图块",
  "Reset all properties to defaults": "将所有属性重置为默认值",
  "Apply current properties to the selected tiles": "将当前属性应用到选中的图块",
  "Apply to Selection": "应用到选择",
  "Tile Property Presets": "图块属性预设",

  // ── Shadow config popup ──────────────────────────────────────────────────
  "Edit Shadow": "编辑阴影",
  "Generate Shadow": "生成阴影",
  "Shadow name": "阴影名称",
  "(auto-named)": "（自动命名）",
  "Tint": "色调",
  "Offset X": "X 偏移",
  "Offset Y": "Y 偏移",
  "3D shadow (second cast anchored at sprite top)": "3D 阴影（第二次投影锚定在精灵图顶部）",
  "Generate per tile (one shadow per source tile)": "逐图块生成（每个源图块一个阴影）",
  "2nd Offset X": "第二个 X 偏移",
  "2nd Offset Y": "第二个 Y 偏移",
  "Preview shown on map. Disconnected groups split into separate shadows.": "在地图上显示预览。断开的组会拆分为单独的阴影。",
  "Generating...": "生成中…",
  "Generate": "生成",
  "Shadow Presets": "阴影预设",

  // ── Fog / graphic-layer config popup ─────────────────────────────────────
  "Layer": "图层",
  "Edit {noun}": "编辑{noun}",
  "Add {noun}": "添加{noun}",
  "{noun} name (optional)": "{noun} 名称（可选）",
  "Graphic": "图形",
  "Choose a graphic from Graphics/{folder}": "从 Graphics/{folder} 中选择图形",
  "(none) — click to choose…": "未选择",
  "Clear graphic": "清除图形",
  "Hue": "色调",
  "Blend Type": "混合类型",
  "Normal": "正常",
  "Add": "添加",
  "Add new…": "添加新…",
  "Color": "颜色",
  "Subtract": "减去",
  "Multiply": "相乘",
  "Scroll X": "滚动 X",
  "Scroll Y": "滚动 Y",
  "Follow camera": "跟随镜头",
  "Parallax": "视差",
  "How fast the layer moves with the camera: 1 = with the map, 0.5 = half speed (RMXP panorama), 0 = fixed on screen": "图层随镜头移动的速度：1 = 随地图，0.5 = 半速（RMXP 全景图），0 = 固定在屏幕上",
  "Preview shown on map": "在地图上显示预览",
  "Select {noun} Graphic": "选择 {noun} 图形",

  // ── Presets dialog ───────────────────────────────────────────────────────
  "Presets": "预设",
  "Renamed \"{old}\" → \"{new}\"": "已重命名 \"{old}\" → \"{new}\"",
  "Overwrite preset?": "覆盖预设？",
  "Replace \"{name}\" with the current values?\nThis cannot be undone.": "用当前值替换 \"{name}\"？\n此操作无法撤销。",
  "Overwrite": "覆盖",
  "Preset \"{name}\" overwritten": "预设 \"{name}\" 已覆盖",
  "Delete preset?": "删除预设？",
  "Delete preset \"{name}\"?\nThis cannot be undone.": "删除预设 \"{name}\"？\n此操作无法撤销。",
  "Preset \"{name}\" deleted": "预设 \"{name}\" 已删除",
  "Preset \"{name}\" created": "预设 \"{name}\" 已创建",
  "A preset named \"{name}\" already exists. Replace it with the current values?": "名为 \"{name}\" 的预设已存在。用当前值替换它？",
  "Choose a folder to export presets into": "选择要导出预设的文件夹",
  "Exported {count} preset(s)": "已导出 {count} 个预设",
  "Export failed: {error}": "导出失败：{error}",
  "Import failed: {error}": "导入失败：{error}",
  "No presets found in file": "文件中未找到预设",
  "Imported {count} preset(s) ({overwritten} overwritten)": "已导入 {count} 个预设（覆盖 {overwritten} 个）",
  "Imported {count} preset(s)": "已导入 {count} 个预设",
  "{count} file(s) skipped": "跳过 {count} 个文件",
  "Filter…": "筛选…",
  "No presets yet.": "还没有预设。",
  "Save the current values below.": "保存下面的当前值。",
  "No matches.": "无匹配。",
  "Click to select. Double-click to apply.": "点击以选择。双击以应用。",
  "Replace this preset's stored values with the current editor values": "用当前编辑器值替换此预设存储的值",
  "Save the current values as your first preset.": "将当前值保存为你的第一个预设。",
  "Select a preset on the left to apply, rename, overwrite, or delete it.": "在左侧选择预设以应用、重命名、覆盖或删除。",
  "Save current as new": "将当前保存为新预设",
  "Preset name": "预设名称",
  "Merge presets from one or more JSON files": "从一个或多个 JSON 文件合并预设",
  "Import…": "导入…",
  "Choose which presets to export to a folder": "选择要导出到文件夹的预设",
  "Export…": "导出…",
  "Export presets": "导出预设",
  "Select all": "全选",
  "Export": "导出",
  "Export {count}": "导出 {count}",

  // ── Graphic picker ───────────────────────────────────────────────────────
  "Graphic — {folder}": "图形——{folder}",
  "Favourites": "收藏",
  "Browse for an image (under Graphics/)": "浏览图像（位于 Graphics/ 下）",
  "No favourites match.": "没有匹配的收藏。",
  "Reset zoom / pan": "重置缩放/平移",
  "Fit": "适应",
  "Ctrl+scroll zoom · space/middle-drag or scroll to pan": "Ctrl+滚动缩放 · 空格/中键拖拽或滚动以平移",
  "Click or drag to pick tiles · Ctrl+scroll zoom · space/middle-drag or scroll to pan": "点击或拖拽以选取图块 · Ctrl+滚动缩放 · 空格/中键拖拽或滚动以平移",
  "Whole image": "整张图像",
  "Use whole image": "使用整张图像",
  "Using tiles from a tileset as a graphic requires the MakerStudio plugin in-game": "将图块集中的图块用作图形需要游戏中的 MakerStudio 插件",
  "Double-click to type a value": "双击以输入值",
  "Blending": "混合",
  "Row": "行",
  "Column": "列",
  "Sheet Cols": "工作表列数",
  "Sheet Rows": "工作表行数",
  "Non-4×4 character sheets require the MakerStudio plugin in-game": "非 4×4 的角色工作表需要游戏中的 MakerStudio 插件",

  // ── Location picker ──────────────────────────────────────────────────────
  "Location": "位置",
  "No maps": "没有地图",
  "{id}: {name} — click a tile": "{id}：{name}——点击一个图块",
  "Pick a map": "选择地图",
  "{key}/Middle-click drag to pan • Ctrl+scroll to zoom • Click to select": "{key}/中键拖拽以平移 • Ctrl+滚动以缩放 • 点击以选择",
  "Select a map from the list": "从列表中选择地图",

  // ── Database dialog ──────────────────────────────────────────────────────
  "Switches": "开关",
  "Variables": "变量",
  "Animations": "动画",
  "Common Events": "公共事件",
  "Discard changes?": "放弃更改？",
  "This tab has unsaved changes. Switch tabs and discard them?": "此标签页有未保存的更改。切换标签页并放弃它们？",
  "This tileset has unsaved changes. Switch tilesets and discard them?": "此图块集有未保存的更改。切换图块集并放弃它们？",
  "Keep editing": "继续编辑",
  "You have unsaved changes. Close the Database and discard them?": "你有未保存的更改。关闭数据库并放弃它们？",
  "Coming soon": "即将推出",
  "Actors": "角色",
  "Classes": "职业",
  "Skills": "技能",
  "Weapons": "武器",
  "Armors": "防具",
  "Enemies": "敌人",
  "Troops": "敌群",
  "States": "状态",
  "System": "系统",

  // ── Common Events tab ────────────────────────────────────────────────────
  "Number of common events:": "公共事件数量：",
  "Loading common events…": "正在加载公共事件…",
  "Failed to load CommonEvents.rxdata:": "加载 CommonEvents.rxdata 失败：",
  "Append one common event": "追加一个公共事件",
  "Set the total count (add or remove from the end)": "设置总数（从末尾添加或移除）",
  "Trigger": "触发条件",
  "None": "无",
  "Parallel": "并行",
  "Condition Switch": "条件开关",
  "Only used by Autorun / Parallel": "仅由自动执行 / 并行使用",
  "Choose condition switch": "选择条件开关",
  "List of Event Commands": "事件命令列表",
  "Select a common event.": "选择一个公共事件。",
  "● Unsaved changes": "● 未保存的更改",
  "Saving…": "保存中…",

  // ── Scripts dialog ───────────────────────────────────────────────────────
  "You have unsaved script changes. Close the editor and discard them?": "你有未保存的脚本更改。关闭编辑器并放弃它们？",
  "Open Data/Scripts in Visual Studio Code": "在 Visual Studio Code 中打开 Data/Scripts",
  "Open in VSC": "在 VSC 中打开",
  "{count} scripts": "{count} 个脚本",
  "Add script": "添加脚本",
  "Delete script": "删除脚本",
  "Move up": "上移",
  "Move down": "下移",
  "Loading…": "加载中…",
  "No scripts.": "没有脚本。",
  "(untitled)": "（无标题）",
  "Select a script to view its code.": "选择一个脚本以查看其代码。",
  "Find in Script": "在脚本中查找",
  "Find in All Scripts": "在所有脚本中查找",
  "Search all scripts…": "搜索所有脚本…",
  "Type to search across all scripts.": "输入以搜索所有脚本。",
  "Invalid regular expression": "无效的正则表达式",
  "{count} results": "{count} 个结果",
  "{count}+ results (showing first {count})": "{count}+ 个结果（显示前 {count} 个）",
  "Too many results — refine your search.": "结果太多——请优化你的搜索。",
  "Find": "查找",
  "Replace": "替换",
  "next": "下一个",
  "previous": "上一个",
  "match case": "区分大小写",
  "by word": "全字匹配",
  "regexp": "正则表达式",
  "replace": "替换",
  "replace all": "全部替换",
  "current match": "当前匹配",
  "on line": "在第",
  "replaced $ matches": "已替换 $ 处匹配",
  "replaced match on line $": "已替换第 $ 行的匹配",

  // ── Version switcher + selector dialog ───────────────────────────────────
  "Active when: {selector}": "激活条件：{selector}",
  "Map Versions": "地图版本",
  "Version:": "版本：",
  "Two versions can be active at once; lower index wins.": "可以同时激活两个版本；索引较小的获胜。",
  "Switch to": "切换到",
  "Rename…": "重命名…",
  "Version Selector — Version {n}: {name}": "版本设置——版本 {n}：{name}",
  "Choose what makes this version active in-game.": "选择什么使此版本在游戏中激活。",
  "Variable equals a value": "变量等于一个值",
  "Switch is ON": "开关为 ON",
  "Pick by id / name": "按 id / 名称选择",
  "Equals value": "等于值",
  "Active while Switch {label} is ON.": "当开关 {label} 为 ON 时激活。",
  "Active while Variable {label} = {value}.": "当变量 {label} = {value} 时激活。",
  "Pick Switch": "选择开关",
  "Pick Variable": "选择变量",

  // ── Version Manager + New Version dialogs ────────────────────────────────
  "Currently editing this version": "当前正在编辑此版本",
  "Click to switch the canvas to this version": "点击将画布切换到此版本",
  "Currently editing": "当前正在编辑",
  "This version's selector can fire at the same time as another's. Lower version number wins.": "此版本的选择器可能与另一个同时触发。版本号较小的获胜。",
  "Always available — used when no version's selector matches.": "始终可用——在没有版本的选择器匹配时使用。",
  "editing": "编辑中",
  "Set the switch/variable that activates this version": "设置激活此版本的开关/变量",
  "Rename version": "重命名版本",
  "Delete this version": "删除此版本",
  "Map Versions — {name}": "地图版本——{name}",
  "New Version": "新版本",
  "Two or more versions can be active at once; the lower version number wins.": "可以同时激活两个或更多版本；版本号较小的获胜。",
  "{count} selector conflict(s)": "{count} 个选择器冲突",
  "A version swaps the whole map (tiles + events + layers) in-game when its selector matches. Base is the fallback. Versions are checked low number → high; the first match wins.": "按版本号从小到大匹配，先满足条件的版本先启用，后续版本不再匹配；匹配成功时，会在游戏时切换地图版本，影响图块、事件、图层。如没有满足条件的版本，则使用基础版本。",
  "Done": "完成",
  "New Map Version": "新地图版本",
  "Start from": "起始于",
  "Duplicate an existing version": "复制现有版本",
  "Blank (empty map)": "空白（空地图）",
  "Creates an empty version (no tiles or events) at the same size as the base map. Bind a switch/variable afterward in the Version Manager.": "创建一个与基础地图大小相同的空版本（无图块或事件），之后在版本管理器中绑定开关/变量条件。",
  "Copies the chosen version's tiles, events and layers into the new version. Bind a switch/variable afterward in the Version Manager.": "将所选版本的图块、事件和图层复制到新版本中，之后在版本管理器中绑定开关/变量条件。",

  // ── Marketplace ──────────────────────────────────────────────────────────
  "Open a project before installing into Project Mods.": "在安装到项目模组之前请先打开一个项目。",
  "Marketplace": "市场",
  "Search mods…": "搜索模组…",
  "Sort order": "排序方式",
  "Stars": "星标",
  "Updated": "更新日期",
  "Ascending — click for descending": "升序——点击切换为降序",
  "Descending — click for ascending": "降序——点击切换为升序",
  "Sort ascending": "升序排序",
  "Sort descending": "降序排序",
  "Refreshing…": "刷新中…",
  "Refresh": "刷新",
  "Matching ANY selected tag — click to require ALL": "匹配任何选中的标签——点击以要求全部",
  "Matching ALL selected tags — click to allow ANY": "匹配所有选中的标签——点击以允许任意",
  "any": "任意",
  "all": "全部",
  "Remove #{tag}": "移除 #{tag}",
  "Add #{tag} ({count} mods)": "添加 #{tag}（{count} 个模组）",
  "Could not load registry: {error}": "无法加载注册表：{error}",
  "Loading registry…": "正在加载注册表…",
  "No mods match your search.": "没有模组匹配你的搜索。",
  "Installed": "已安装",
  "Install": "安装",
  "Open mod repo on GitHub": "在 GitHub 上打开模组仓库",
  "Open on GitHub": "在 GitHub 上打开",
  "Changelog": "更新日志",
  "by": "作者",
  "Release SHA-256 matches the registry pin.": "发布版 SHA-256 与注册表固定值匹配。",
  "Verified": "已验证",
  "Release bytes do not match the registry's pinned SHA-256. Install will be blocked.": "发布版字节与注册表的固定 SHA-256 不匹配。安装将被阻止。",
  "Tampered": "已篡改",
  "Hashing the pinned release asset…": "正在计算固定发布版资产的哈希…",
  "Checking…": "检查中…",
  "Could not reach the release to verify its SHA-256.": "无法访问发布版以验证其 SHA-256。",
  "Unverified": "未验证",
  "SHA-256 not yet checked.": "尚未检查 SHA-256。",
  "Fetching…": "获取中…",
  "Downloading…": "下载中…",
  "Verifying…": "验证中…",
  "Installing…": "安装中…",
  "Removing…": "移除中…",
  "Changelog — {mod} v{version}": "更新日志——{mod} v{version}",
  "No changelog.": "没有更新日志。",

  // ── Keyboard shortcuts dialog ────────────────────────────────────────────
  "Keyboard Shortcuts": "键盘快捷键",
  "Search shortcuts...": "搜索快捷键…",
  "{key} is bound to {actions}. Allow duplicate?": "{key} 已绑定到 {actions}。允许重复？",
  "Keep": "保留",
  "Swap": "交换",
  "{key} is also used by: {actions}. Update all to {newKey}?": "{key} 也被以下使用：{actions}。全部更新为 {newKey}？",
  "Update All": "全部更新",
  "Only This": "仅此",
  "{key} is bound to {label}. Allow duplicate?": "{key} 已绑定到 {label}。允许重复？",
  "Press a key...": "按下一个键…",
  "Reset to default": "重置为默认",
  "Reset All": "全部重置",
  "Search Results": "搜索结果",
  "Event Editor": "事件编辑器",
  "Simulator": "模拟器",
  "App": "应用",
  "Dev": "开发",
  "Pan (Hold)": "平移（按住）",
  "Toggle Grid": "切换网格",
  "Toggle Collision": "切换碰撞",
  "Toggle Dim": "切换淡化",
  "Toggle Event Cells": "切换事件格",
  "Drag to resize the autotiles list": "拖拽以调整自动图块列表大小",
  "Brush Size Up": "增大画笔大小",
  "Brush Size Down": "减小画笔大小",
  "Toggle Custom Brush": "切换自定义画笔",
  "Use Selection as Brush": "使用选择作为画笔",
  "Clear Tile Selection": "清除图块选择",
  "Layer 1": "图层 1",
  "Layer 2": "图层 2",
  "Layer 3": "图层 3",
  "Layer 4": "图层 4",
  "Layer 5": "图层 5",
  "Layer 6": "图层 6",
  "Layer 7": "图层 7",
  "Layer 8": "图层 8",
  "Layer 9": "图层 9",
  "Events Layer": "事件图层",
  "Previous Layer": "上一图层",
  "Next Layer": "下一图层",
  "Toggle Layer 1": "切换图层 1 显示/隐藏",
  "Toggle Layer 2": "切换图层 2 显示/隐藏",
  "Toggle Layer 3": "切换图层 3 显示/隐藏",
  "Toggle Layer 4": "切换图层 4 显示/隐藏",
  "Toggle Layer 5": "切换图层 5 显示/隐藏",
  "Toggle Layer 6": "切换图层 6 显示/隐藏",
  "Toggle Layer 7": "切换图层 7 显示/隐藏",
  "Toggle Layer 8": "切换图层 8 显示/隐藏",
  "Toggle Layer 9": "切换图层 9 显示/隐藏",
  "Toggle Events Layer": "切换事件图层显示/隐藏",
  "Save All Maps": "保存所有地图",
  "Create Shadow from Selection": "从选择创建阴影",
  "Paste All Layers": "粘贴所有图层",
  "Edit Command": "编辑命令",
  "Insert Command": "插入命令",
  "Move Command Up": "上移",
  "Move Command Down": "下移",
  "Previous Command": "上一命令",
  "Next Command": "下一命令",
  "Play / Pause": "播放 / 暂停",
  "Step One Frame": "运行一帧",
  "Close Simulator": "关闭模拟器",
  "OK / Action Button": "确定 / 确定键",
  "Player Up": "玩家向上",
  "Player Down": "玩家向下",
  "Player Left": "玩家向左",
  "Player Right": "玩家向右",
  "Toggle Camera Mode": "切换镜头模式",
  "Reset App": "重置应用",

  // ── Tileset manager ──────────────────────────────────────────────────────
  "Failed to create tileset: {error}": "创建图块集失败：{error}",
  "Failed to update tileset: {error}": "更新图块集失败：{error}",
  "Failed to delete tileset: {error}": "删除图块集失败：{error}",
  "No tilesets found.": "未找到图块集。",
  "New Tileset": "新建图块集",
  "Name:": "名称：",
  "Tileset name": "图块集名称",
  "Graphic:": "图形：",
  "Browse...": "浏览…",
  "Creating...": "创建中…",
  "Type:": "类型：",
  "Virtual — autotile properties shared across all tilesets": "不存在——自动图块集可在所有图块集间使用",
  "Autotiles:": "自动图块：",
  "{count} assigned": "已分配 {count} 个",
  "Edit Name/Graphic": "编辑名称/图形",
  "Rename tileset": "重命名图块集",
  "Change graphic": "更换图形",
  "Select a tileset to view details, or create a new one.": "选择一个图块集以查看详细信息，或创建一个新的。",
  "Delete Tileset": "删除图块集",
  "Delete tileset": "删除图块集",
  "Any maps using this tileset will lose their tile data. This cannot be undone.": "任何使用此图块集的地图都会丢失其图块数据。此操作无法撤销。",
  "Deleting...": "删除中…",
  "Choose Graphic": "选择图形",
  "Tilesets": "图块集",

  // ── Tileset editor ───────────────────────────────────────────────────────
  "Filter...": "筛选…",
  "No match": "无匹配",
  "Tileset: {name}": "图块集：{name}",
  "Mode": "模式",
  "Col {col}, Row {row}": "列 {col}，行 {row}",
  "Pass:": "通行：",
  "Pri:": "优先：",
  "Ter:": "地形：",
  "Hover a tile": "悬停在一个图块上",
  "Open Autotiles Folder": "打开自动图块文件夹",
  "Terrain Tag": "地形标签",
  "Set {count} tiles": "设置 {count} 个图块",
  "Click tile to set": "点击图块以设置",
  "Batch": "批量",
  "Toggle all ({count})": "全部切换（{count}）",
  "Reset all": "全部重置",
  "Batch Direction": "批量方向",
  "Toggle Up": "切换上方",
  "Toggle Left": "切换左侧",
  "Toggle Right": "切换右侧",
  "Toggle Down": "切换下方",
  "Selection": "选择",
  "{count} tiles": "{count} 个图块",
  "Click": "点击",
  "apply": "应用",
  "Right-click": "右键",
  "menu/reset": "菜单/重置",
  "Ctrl+Drag": "Ctrl+拖拽",
  "select": "选择",
  "Shift+Click": "Shift+点击",
  "unselect": "取消选择",
  "clear": "清除",
  "undo": "撤销",
  "redo": "重做",
  "Open": "开启",
  "Blocked": "禁止",
  "Partial": "部分",
  "{count} tiles selected": "已选择 {count} 个图块",
  "Tile ({col}, {row})": "图块（{col}，{row}）",
  "Toggle": "切换",
  "Passage": "通行",
  "Passage (4 dir)": "通行（4 方向）",
  "Bush Flag": "灌木标志",
  "Counter Flag": "柜台标志",

  // ── Animations tab ───────────────────────────────────────────────────────
  "Number of animations:": "动画数量：",
  "Change Frame Count": "更改帧数",
  "Number of frames:": "帧数：",
  "Loading animations…": "正在加载动画…",
  "Failed to load Animations.rxdata:": "加载 Animations.rxdata 失败：",
  "Append one animation": "追加一个动画",
  "Top": "顶部",
  "Middle": "中间",
  "Bottom": "底部",
  "Screen": "屏幕",
  "Frames": "帧",
  "Previous frame": "上一帧",
  "Frame {n} / {total}": "帧 {n} / {total}",
  "Next frame": "下一帧",
  "Undo (Ctrl+Z)": "撤销（Ctrl+Z）",
  "Redo (Ctrl+Y)": "重做（Ctrl+Y）",
  "Onion": "洋葱皮",
  "+ Frame": "+ 帧",
  "Copy the previous frame's cells here": "将上一帧的单元格复制到这里",
  "Paste Last": "使用上一帧",
  "Copy this frame's cells": "复制此帧的单元格",
  "Copy Frame": "复制帧",
  "Paste copied frame cells here": "将复制的帧单元格粘贴到这里",
  "Paste Frame": "粘贴帧",
  "Remove all cells in this frame": "移除此帧中的所有单元格",
  "Clear Frame": "清除帧",
  "Tweening…": "补间…",
  "Cell Batch…": "单元格批处理…",
  "Entire Slide…": "处理整个幻灯片…",
  "Select an animation.": "选择一个动画。",
  "Cells: {count}": "单元格：{count}",
  "Dup": "复制",
  "Del": "删除",
  "Angle": "角度",
  "Blend": "混合",
  "Mirror": "镜像",
  "Click a cell on the canvas, or pick a pattern from the sheet to add one.": "点击画布上的一个单元格，或从工作表中选取一个图案以添加。",
  "Sheet": "工作表",
  "— click to set the selected cell's pattern": "——点击以设置所选单元格的图案",
  "Animation Graphic": "动画图形",

  // ── Permissions consent modal ────────────────────────────────────────────
  "Install: {name}": "安装：{name}",
  "This mod is not maintainer-verified. The release bytes will still be SHA-256 checked against the registry, but you are trusting the author code.": "此模组未经维护者验证。发布版字节仍会与注册表进行 SHA-256 校验，但你是在信任作者的代码。",
  "This mod requests the following capabilities:": "此模组请求以下权限：",
  "No permissions declared.": "未声明权限。",
  "Read/write inside its own mod folder": "在其自己的模组文件夹内读写",
  "Read project files (game folder)": "读取项目文件（游戏文件夹）",
  "Write to project files (modify game data)": "写入项目文件（修改游戏数据）",
  "Cancel save operations": "取消保存操作",
  "Show dialogs": "显示对话框",
  "Show toasts": "显示通知",
  "Install location:": "安装位置：",
  "Open a project first": "请先打开一个项目",
  "Install into this project's Mods folder": "安装到此项目的 Mods 文件夹",
  "(no project open)": "（未打开项目）",
  "Install into global Mods folder (all projects)": "安装到全局 Mods 文件夹（所有项目）",
  "I understand this is unverified code from the internet.": "我理解这是来自互联网的未验证代码。",
  "Install Unverified": "安装未验证",

  // ── Event editor chrome ──────────────────────────────────────────────────
  "Clone Page": "克隆页",
  "Delete Page": "删除页",
  "Event - ID:{id}": "事件 - ID:{id}",
  "New page": "新页",
  "Delete page": "删除页",
  "Open Game Simulator on this event page": "在此事件页上打开游戏模拟器",
  "Simulate": "模拟",
  "Conditions": "条件",
  "ON": "ON",
  "OFF": "OFF",
  "Self Switch": "独立开关",
  "Click to choose character graphic": "点击以选择角色图形",
  "Change…": "更改…",
  "Autonomous Movement": "自主移动",
  "Fixed": "固定",
  "Random": "随机",
  "Approach": "靠近玩家",
  "Frequency": "频率",
  "Slowest": "最慢",
  "Slower": "较慢",
  "Slow": "慢",
  "Fast": "快",
  "Faster": "较快",
  "Fastest": "最快",
  "Lowest": "最低",
  "Lower": "较低",
  "Low": "低",
  "High": "高",
  "Highest": "最高",
  "Options": "选项",
  "Move Animation": "移动动画",
  "Stop Animation": "停止动画",
  "Direction Fix": "固定方向",
  "Through": "穿透",
  "Block": "阻挡",
  "Always impassable, even for Tile Graphic pages whose underlying tile would otherwise be walkable": "始终不可通行，即使对于底层图块本可通行的图块图形页也是如此",
  "Drag to resize": "拖拽以调整大小",
  "Always on Top": "始终置顶",
  "Always on Bottom": "始终置底",
  "Always on Bottom requires the MakerStudio plugin in-game": "始终置底需要游戏中的 MakerStudio 插件",
  "Insert command": "插入命令",
  "+ Insert": "+ 插入",
  "Edit selected command": "编辑选中的命令",
  "Insert below": "在下方插入",
  "Insert above": "在上方插入",
  "Cut ({count})": "剪切（{count}）",
  "Copy ({count})": "复制（{count}）",
  "Delete ({count})": "删除（{count}）",
  "Move Command": "移动命令",

  // ── Set Move Route (209): route options + the move-action buttons ──────────
  "Target (-1 = Player, 0 = this event)": "目标（-1 = 玩家，0 = 此事件）",
  "Repeat Action": "重复动作",
  "Ignore If Can't Move": "无法移动时忽略",
  "Frame (Maker Studio)": "帧（Maker Studio）",
  "Set Frame…": "设置帧…",
  "Set Column (horizontal frame)": "设置列（水平帧）",
  "Set Row (vertical frame)": "设置行（垂直帧）",
  "{n} frames": "{n} 帧",
  "End": "结束",
  "Move Down": "向下移动",
  "Move Left": "向左移动",
  "Move Right": "向右移动",
  "Move Up": "向上移动",
  "Move Lower Left": "向左下移动",
  "Move Lower Right": "向右下移动",
  "Move Upper Left": "向左上移动",
  "Move Upper Right": "向右上移动",
  "Move at Random": "随机移动",
  "Move toward Player": "移向玩家",
  "Move away from Player": "远离玩家",
  "1 Step Forward": "前进 1 步",
  "1 Step Backward": "后退 1 步",
  "Jump…": "跳跃…",
  "Wait…": "等待…",
  "Turn Down": "转向下",
  "Turn Left": "转向左",
  "Turn Right": "转向右",
  "Turn Up": "转向上",
  "Turn 90° Right": "右转 90°",
  "Turn 90° Left": "左转 90°",
  "Turn 180°": "转 180°",
  "Turn 90° Right or Left": "右转或左转 90°",
  "Turn at Random": "随机转向",
  "Turn toward Player": "转向玩家",
  "Turn away from Player": "背对玩家",
  "Switch ON…": "开关 ON…",
  "Switch OFF…": "开关 OFF…",
  "Change Speed…": "更改速度…",
  "Change Freq…": "更改频率…",
  "Move Animation ON": "移动动画 ON",
  "Move Animation OFF": "移动动画 OFF",
  "Stop Animation ON": "停止动画 ON",
  "Stop Animation OFF": "停止动画 OFF",
  "Direction Fix ON": "固定方向 ON",
  "Direction Fix OFF": "固定方向 OFF",
  "Through ON": "穿透 ON",
  "Through OFF": "穿透 OFF",
  "Always on Top ON": "始终置顶 ON",
  "Always on Top OFF": "始终置顶 OFF",
  "Change Graphic…": "更改图形…",
  "Change Opacity…": "更改不透明度…",
  "Change Blending…": "更改混合…",
  "Play SE…": "播放 SE…",
  "Script…": "脚本…",

  // ── RPG Maker event command names ─────────────────────────────────────────
  "Show Text": "显示文字",
  "Show Choices": "显示选项",
  "Input Number": "输入数字",
  "Change Text Options": "更改文字选项",
  "Button Input Processing": "按钮输入处理",
  "Wait": "等待",
  "Comment": "注释",
  "Conditional Branch": "条件分支",
  "Break Loop": "跳出循环",
  "Exit Event Processing": "退出事件处理",
  "Erase Event": "擦除事件",
  "Call Common Event": "调用公共事件",
  "Label": "标签",
  "Jump to Label": "跳转到标签",
  "Control Switches": "控制开关",
  "Control Variables": "控制变量",
  "Control Self Switch": "控制独立开关",
  "Control Timer": "控制计时器",
  "Change Gold": "更改金钱",
  "Change Items": "更改道具",
  "Change Weapons": "更改武器",
  "Change Armor": "更改防具",
  "Change Party Member": "更改队伍成员",
  "Change Windowskin": "更改窗口皮肤",
  "Change Battle BGM": "更改对战 BGM",
  "Change Battle End ME": "更改对战结束 ME",
  "Change Save Access": "更改存档权限",
  "Change Menu Access": "更改菜单权限",
  "Change Encounter": "更改遭遇",
  "Transfer Player": "移动玩家",
  "Set Event Location": "设置事件位置",
  "Scroll Map": "滚动地图",
  "Change Map Settings": "更改地图设置",
  "Change Fog Color Tone": "更改迷雾色调",
  "Change Fog Opacity": "更改迷雾不透明度",
  "Show Animation": "显示动画",
  "Change Transparent Flag": "更改透明标志",
  "Set Move Route": "设置移动路线",
  "Set Move Route...": "设置移动路线…",
  "Dark Mode (set by theme)": "深色模式（由主题设置）",
  "min {w}×{h}": "最小 {w}×{h}",
  "the screen the pointer is on": "指针所在的屏幕",
  "Settings...": "设置…",
  "Window size at startup": "启动时的窗口大小",
  "1400 × 900, centred — what it does today": "1400 × 900，居中——当前行为",
  "Remember last size and position": "记住上次的大小和位置",
  "Maximized": "最大化",
  "Fullscreen": "全屏",
  "Specific size": "指定大小",
  "Which monitor": "哪个显示器",
  "The one it is launched from": "启动它的那个",
  "The last one it was closed on": "上次关闭时的那个",
  "Always this monitor": "始终使用此显示器",
  "(no monitors reported)": "（未检测到显示器）",
  "primary": "主显示器",
  "A monitor that is not connected falls back to the one Maker Studio is launched from.": "未连接的显示器会回退到 Maker Studio 启动时所在的显示器。",
  "Which monitor the game opens on": "游戏在哪个显示器上打开",

  "Alt+Click: show only this layer": "Alt+点击：仅显示此图层",
  "You have unsaved settings. Discard them?": "你有未保存的设置。放弃它们？",

  // ── Settings → Appearance (theme editor) ──────────────────────────────────
  "Appearance": "外观",
  "Dark mode": "深色模式",
  "this theme sets the mode itself": "此主题自行设置模式",
  "Colours": "颜色",
  "Colours are saved per theme and per light/dark mode.": "颜色按主题和浅色/深色模式分别保存。",
  "Dark": "深色",
  "Light": "浅色",
  "Filter colours…": "筛选颜色…",
  "No changes": "无更改",
  "Reset {count} changes": "重置 {count} 处更改",
  "Pick a colour": "选择一种颜色",
  "Back to the theme's colour": "返回主题的颜色",
  "Surfaces": "表面",
  "Text": "文字",
  "Accent": "强调色",
  "Status": "状态",
  "Map canvas": "地图画布",
  "Event commands": "事件命令",
  "Colours of the command list in the event editor.": "事件编辑器中命令列表的颜色。",
  "Script editor": "脚本编辑器",
  "Ruby syntax highlighting in the Scripts window.": "脚本窗口中的 Ruby 语法高亮。",
  "Background": "背景",
  "Controls": "控件",
  "Hover": "悬停",
  "Inputs": "输入框",
  "Borders": "边框",
  "Primary": "主要",
  "Secondary": "次要",
  "Muted": "弱化",
  "Accent hover": "强调色悬停",
  "Accent tint": "强调色淡染",
  "Text on accent": "强调色上的文字",
  "Danger": "危险",
  "Warning": "警告",
  "Highlight": "高亮",
  "Success": "成功",
  "Success hover": "成功悬停",
  "Success border": "成功边框",
  "Canvas background": "画布背景",
  "Checker light": "图块集浅色背景",
  "Checker dark": "图块集深色背景",
  "Conditional": "条件",
  "Flow": "流程",
  "Switches / variables": "开关 / 变量",
  "Party": "队伍",
  "Move route": "移动路线",
  "Move step": "移动步骤",
  "Picture": "图片",
  "Uncategorised": "未分类",
  "Terminator": "终止符",
  "Keyword": "关键字",
  "String": "字符串",
  "Definition": "定义",
  "Meta": "元",
  "The same one as the editor": "与编辑器相同的那个",
  "the screen Maker Studio is on right now": "Maker Studio 当前所在的屏幕",
  "Applies the next time you run the game. RPG Maker re-centres its own window on the primary screen while the game boots, so it can jump for a few seconds before it settles.": "在下次运行游戏时生效。游戏启动时，RPG Maker 会将其窗口重新居中到主屏幕，因此可能会在稳定前跳动几秒。",
  "Windows only — the game runs through Wine/Proton here, where its window cannot be placed by the editor.": "仅限 Windows——这里游戏通过 Wine/Proton 运行，编辑器无法放置其窗口。",
  "Editor": "编辑器",
  "Game": "游戏",
  "Restore defaults": "恢复默认值",
  "Settings saved — they apply the next time Maker Studio starts.": "设置已保存——它们将在下次 Maker Studio 启动时生效。",
  "Could not save settings: {error}": "无法保存设置：{error}",
  "Value 1 (first)": "值 1（第一个）",
  "Value 2": "值 2",
  "Value 3": "值 3",
  "Value 4": "值 4",
  "Value 5": "值 5",
  "Value 6": "值 6",
  "Value 7": "值 7",
  "Value 8": "值 8",
  "Value 9": "值 9",
  "Value 10 (tenth)": "值 10（第十个）",
  "Tileset Editor": "图块集编辑器",
  "Any Event (RPG Maker default)": "任何事件（RPG Maker 默认）",
  "Waits only for the route this event set on that event. Without the MakerStudio plugin the game falls back to waiting for every character.": "只等待此事件在该事件上设置的路线。没有 MakerStudio 插件时，游戏会回退为等待每个角色。",
  "Waits for the Set Move Route commands this event ran, whoever they moved. Without the MakerStudio plugin the game falls back to waiting for every character.": "等待此事件运行的设置移动路线命令，无论它们移动了谁。没有 MakerStudio 插件时，游戏会回退为等待每个角色。",
  "This folder is empty.": "此文件夹为空。",
  "It holds {count} preset(s). Choose what happens to them.": "它包含 {count} 个预设。选择如何处理它们。",
  "Keep presets": "保留预设",
  "Delete both": "两者都删除",
  "The presets move back out of the folder": "预设会移出文件夹",
  "Rename Folder…": "重命名文件夹…",
  "Delete Folder…": "删除文件夹…",
  "Delete folder": "删除文件夹",
  "Folder only": "仅文件夹",
  "Folder and presets": "文件夹和预设",
  "Empty — drop a preset here": "空——将预设拖放到此处",
  "Drop here to take a preset out of its folder": "拖放到此处以将预设移出其文件夹",
  "Click to fold. Right-click for folder options. Drop a preset here to file it.": "点击以折叠。右键打开文件夹选项。将预设拖放到此处以归档。",
  "Click to select. Double-click to apply. Drag onto a folder to file it.": "点击以选择。双击以应用。拖到文件夹上以归档。",
  "Delete the folder \"{name}\"? Its presets can stay.": "删除文件夹 \"{name}\"？其预设可以保留。",
  "Release bytes do not match the registry's pinned SHA-256. Install is blocked.": "发布版字节与注册表的固定 SHA-256 不匹配。安装已被阻止。",
  "Show Dependency Warnings Again": "显示依赖警告",
  "Open saved-games folder (~/.local/share/<Game>)": "打开存档文件夹（~/.local/share/<Game>）",
  "Search mods, authors, tags…": "搜索模组、作者、标签…",
  "Card view": "卡片视图",
  "Compact list — more mods per screen": "紧凑列表——每屏更多模组",
  "Compact list": "紧凑列表",
  "Re-fetch the registry": "重新获取注册表",
  "Updates": "更新",
  "Tags": "标签",
  "Filter tags…": "筛选标签…",
  "Match": "匹配",
  "Any": "任意",
  "All": "全部",
  "No tags match.": "没有匹配的标签。",
  "any of": "任意一个",
  "all of": "全部",
  "{count} mods": "{count} 个模组",
  "{count} of {total}": "{count} / {total}",
  "Clear filters": "清除筛选",
  "Everything is up to date.": "一切都已是最新。",
  "No mods installed yet.": "尚未安装模组。",
  "No mods match these filters.": "没有模组匹配这些筛选条件。",
  "Show {count} more": "再显示 {count} 个",
  "Filter by #{tag}": "按 #{tag} 筛选",
  "A mod matches if it has any of the selected tags": "模组在具有任何选中的标签时匹配",
  "A mod matches only if it has all of the selected tags": "模组只有在具有所有选中的标签时才匹配",
  "New preset or folder": "新预设或文件夹",
  "New Preset…": "新预设…",
  "New Folder…": "新文件夹…",
  "Folder name": "文件夹名称",
  "Moved \"{preset}\" into \"{folder}\"": "已将 \"{preset}\" 移入 \"{folder}\"",
  "Folder \"{folder}\" created with the current values": "已使用当前值创建文件夹 \"{folder}\"",
  "Wait for": "等待",
  "Waiting for one character requires the MakerStudio plugin in-game": "等待一个角色需要游戏中的 MakerStudio 插件",
  "Waits until no character on the map is following a forced move route — the stock behaviour, plugin not required.": "等待地图上没有角色再跟随强制移动路线——原始行为，不需要插件。",
  "Waits only for this character. Without the MakerStudio plugin the game falls back to waiting for every character.": "只等待此角色。没有 MakerStudio 插件时，游戏会回退为等待每个角色。",
  "Browse and preview the project's audio files": "浏览并预览项目的音频文件",
  "Theme": "主题",
  "Audio Browser...": "音频浏览器…",
  "Audio Browser": "音频浏览器",
  "Folder": "文件夹",
  "Rename folder": "重命名文件夹",
  "Rename this folder everywhere it is used": "在所有使用处重命名此文件夹",
  "Show or hide this folder": "显示或隐藏此文件夹",
  "Save the current values as a new preset": "将当前值保存为新预设",
  "Click to select. Double-click to apply. Drag to reorder or move between folders.": "点击以选择。双击以应用。拖拽以重新排序或在文件夹之间移动。",
  "Wait for Move's Completion": "等待移动完成",
  "Prepare for Transition": "准备渐变",
  "Execute Transition": "执行渐变",
  "Change Screen Color Tone": "更改屏幕色调",
  "Screen Flash": "屏幕闪烁",
  "Screen Shake": "屏幕震动",
  "Show Picture": "显示图片",
  "Move Picture": "移动图片",
  "Rotate Picture": "旋转图片",
  "Change Picture Color Tone": "更改图片色调",
  "Erase Picture": "消除图片",
  "Set Weather Effects": "设置天气效果",
  "Play BGM": "播放 BGM",
  "Fade Out BGM": "淡出 BGM",
  "Play BGS": "播放 BGS",
  "Fade Out BGS": "淡出 BGS",
  "Memorize BGM/BGS": "记忆 BGM/BGS",
  "Restore BGM/BGS": "恢复 BGM/BGS",
  "Play ME": "播放 ME",
  "Play SE": "播放 SE",
  "Stop SE": "停止 SE",
  "Battle Processing": "对战处理",
  "Shop Processing": "商店处理",
  "Name Input Processing": "名称输入处理",
  "Change HP": "更改 HP",
  "Change SP": "更改 SP",
  "Change State": "更改状态",
  "Recover All": "全部恢复",
  "Change EXP": "更改 EXP",
  "Change Level": "更改等级",
  "Change Parameters": "更改参数",
  "Change Skills": "更改技能",
  "Change Equipment": "更改装备",
  "Change Actor Name": "更改角色名称",
  "Change Actor Class": "更改角色职业",
  "Change Actor Graphic": "更改角色图形",
  "Change Enemy HP": "更改敌人 HP",
  "Change Enemy SP": "更改敌人 SP",
  "Change Enemy State": "更改敌人状态",
  "Enemy Recover All": "敌人全部恢复",
  "Enemy Appearance": "敌人出现",
  "Enemy Transform": "敌人变身",
  "Show Battle Animation": "显示对战动画",
  "Deal Damage": "造成伤害",
  "Force Action": "强制行动",
  "Abort Battle": "中止对战",
  "Call Menu Screen": "调用菜单屏幕",
  "Call Save Screen": "调用存档屏幕",
  "Game Over": "游戏结束",
  "Return to Title Screen": "返回标题屏幕",
  "Script": "脚本",
  "Jump": "跳跃",
  "Switch ON": "开关 ON",
  "Switch OFF": "开关 OFF",
  "Change Speed": "更改速度",
  "Change Freq": "更改频率",
  "Change Graphic": "更改图形",
  "Change Opacity": "更改不透明度",
  "Change Blending": "更改混合",

  // ── Command picker ───────────────────────────────────────────────────────
  "Event Commands": "事件命令",
  "Search commands...": "搜索命令…",
  "Messages": "消息",
  "Text, choices, number input, waits.": "文字、选项、数字输入、等待。",
  "Logic": "逻辑",
  "Conditions, loops, labels, switches, variables, timer.": "条件、循环、标签、开关、变量、计时器。",
  "Party & Items": "队伍与道具",
  "Gold, items, weapons, armor, party members.": "金钱、道具、武器、防具、队伍成员。",
  "Movement": "移动",
  "Transfers, move routes, animations, map scroll & fog.": "移动、移动路线、动画、地图滚动与迷雾。",
  "Screen & Pictures": "屏幕与图片",
  "Transitions, tones, flash, shake, pictures, weather.": "渐变、色调、闪烁、震动、图片、天气。",
  "BGM, BGS, ME, SE playback and fades.": "BGM、BGS、ME、SE 的播放与淡入淡出。",
  "HP/SP, states, stats, skills, equipment, name & graphic.": "HP/SP、状态、能力值、技能、装备、名称与图形。",
  "Battle": "对战",
  "Battle & shop processing, enemy changes, force action.": "对战与商店处理、敌人更改、强制行动。",
  "Windowskin, access toggles, menu/save/title screens, script.": "窗口皮肤、权限开关、菜单/存档/标题屏幕、脚本。",
  "Your pinned commands. Use the pencil to reorder them.": "你固定的命令。使用铅笔以重新排序。",
  "Reorder favourites": "重新排序收藏",
  "Done reordering": "完成重新排序",
  "Scroll tabs left": "向左滚动标签",
  "Scroll tabs right": "向右滚动标签",
  "Searching all categories…": "正在搜索所有类别…",
  "No commands match.": "没有匹配的命令。",
  "Remove from favourites": "从收藏中移除",
  "Add to favourites": "添加到收藏",

  // ── Command parameter form ───────────────────────────────────────────────
  "code {code}": "代码 {code}",
  "Favourited": "已收藏",
  "Add Favourite": "添加收藏",
  "Change {title}": "更改 {title}",
  "Edit Row {n}": "编辑第 {n} 行",
  "Parameters (raw JSON)": "参数（原始 JSON）",

  // ── Misc string-form variants ────────────────────────────────────────────
  "More tabs": "更多标签",
  "(none)": "（无）",
  "Append one frame": "追加一帧",
  "Opacity": "不透明度",
  "Autotiles": "自动图块",
  "Search tilesets...": "搜索图块集…",
  "Change Tileset": "更换图块集",

  // ── Command param-form field labels ──────────────────────────────────────
  "Red": "红",
  "Green": "绿",
  "Blue": "蓝",
  "Source": "来源",
  "Map ID": "地图 ID",
  "X": "X",
  "Y": "Y",
  "Map ID Var": "地图 ID 变量",
  "X Var": "X 变量",
  "Y Var": "Y 变量",
  "Ruby code (RGSS / Pokémon Essentials API)": "Ruby 代码（RGSS / Pokémon Essentials API）",
  "Snippets…": "代码片段…",
  "Script Snippets": "脚本片段",
  "Saved script snippets": "已保存的脚本片段",
  "Replace script?": "替换脚本？",
  "This replaces the {lines} line(s) already in this Script command.\nThis cannot be undone.": "这会替换此 Script 命令中已有的 {lines} 行。\n此操作无法撤销。",
  "Message text...": "消息文字…",
  "Remove choice": "移除选项",
  "When Cancel": "取消时",
  "Digits": "位数",
  "Comment text...": "注释文字…",
  "Compare With": "与…比较",
  "Value": "值",
  "Other Variable": "其他变量",
  "Operator": "运算符",
  "Event ID": "事件 ID",
  "Is Facing": "是否面向",
  "Amount": "数量",
  "Comparison": "比较",
  "Ruby expression evaluated to truthy/falsy": "求值为真/假的 Ruby 表达式",
  "Add Else Branch": "添加否则分支",
  "hours": "小时",
  "min": "分",
  "sec": "秒",
  "Condition": "条件",
  "exact actor name": "精确角色名称",
  "Window": "窗口",
  "From": "从",
  "To": "到",
  "Operation": "操作",
  "From Variable": "来自变量",
  "Min": "最小",
  "Max": "最大",
  "Stat": "能力值",
  "Field": "字段",
  "Channel": "通道",
  "Quantity": "数量",
  "Initialize": "初始化",
  "Audio": "音频",
  "Fading": "淡入淡出",
  "Swap with": "与…交换",
  "Distance": "距离",
  "Fog Layer": "迷雾图层",
  "Follow camera (screen-locked)": "跟随镜头（锁定屏幕）",
  "Transition": "渐变",
  "Number": "数字",
  "Picture Graphic": "图片图形",
  "Origin": "原点",
  "Zoom X": "缩放 X",
  "Zoom Y": "缩放 Y",
  "Seconds": "秒",
  "Can Escape": "可以逃跑",
  "Continue Even When Loser": "失败时也继续",
  "Remove": "移除",
  "Kind": "种类",
  "Custom Price (0 = default)": "自定义价格（0 = 默认）",
  "Max Characters": "最大字符数",
  "Allow Knockout in Battle": "允许在对战中倒下",
  "Parameter": "参数",
  "Character Graphic": "角色图形",
  "Battler Graphic": "战斗图形",
  "Transform To": "变身成",
  "Target Kind": "目标种类",
  "Action": "行动",
  "Basic Action": "基本行动",
  "Action Target": "行动目标",
  "Timing": "时机",
  "SE": "SE",

  // ── Command list inline summaries ────────────────────────────────────────
  "(route end)": "（路线结束）",
  "Map: [{mapVar}], X: [{xVar}], Y: [{yVar}]": "地图：[{mapVar}]，X：[{xVar}]，Y：[{yVar}]",
  "Jump: ({x}, {y})": "跳跃：（{x}，{y}）",
  "Wait: {n} frames": "等待：{n} 帧",
  "Change Speed: {n}": "更改速度：{n}",
  "Change Freq: {n}": "更改频率：{n}",
  "Change Graphic: \"{name}\"": "更改图形：\"{name}\"",
  "Change Opacity: {n}": "更改不透明度：{n}",
  "Script: {text}": "脚本：{text}",
  "Choice {n}": "选项 {n}",
  "{label}, {n} digit": "{label}，{n} 位数字",
  "{label}, {n} digits": "{label}，{n} 位数字",
  "Common Event {id}": "公共事件 {id}",
  "Self Switch {ch} = {op}": "独立开关 {ch} = {op}",
  "Switch {label} is {state}": "开关 {label} 为 {state}",
  "Var {label} {op} {rhs}": "变量 {label} {op} {rhs}",
  "Self Switch {ch} is {state}": "独立开关 {ch} 为 {state}",
  "Timer {mode} {sec}s": "计时器 {mode} {sec} 秒",
  "Actor {x}": "角色 {x}",
  "Enemy {x}": "敌人 {x}",
  "Character {x} dir": "角色 {x} 方向",
  "Gold {mode} {amt}": "金钱 {mode} {amt}",
  "Item {x} in inventory": "道具 {x} 在背包中",
  "Weapon {x} in inventory": "武器 {x} 在背包中",
  "Armor {x} in inventory": "防具 {x} 在背包中",
  "Button {x} pressed": "按钮 {x} 被按下",
  "Type {n}": "类型 {n}",
  "Item count": "道具数量",
  "Actor stat": "角色能力值",
  "Enemy stat": "敌人能力值",
  "This Event": "此事件",
  "repeat": "重复",
  "once": "一次",
  "skip-on-block": "受阻时跳过",
  "{n} step": "{n} 步",
  "{n} steps": "{n} 步",

  // ── Animation batch / timing panels ──────────────────────────────────────
  "Frames:": "帧：",
  "Cells:": "单元格：",
  "Tweening Items": "补间项目",
  "Position / Zoom / Angle": "位置 / 缩放 / 角度",
  "Opacity / Blending": "不透明度 / 混合",
  "Flip": "翻转",
  "Movement Amount (per frame)": "移动量（每帧）",

  // ── Simulator ────────────────────────────────────────────────────────────
  "Maker Studio exclusive": "Maker Studio 专属",
  "confirm": "确认",
  "Input Number ({n} digits)": "输入数字（{n} 位）",
  "change": "更改",
  "{key} to advance": "{key} 以继续",
  "(no log entries yet)": "（还没有日志条目）",
  "Logged only — not executed in the simulator": "仅记录——不在模拟器中执行",
  "unsupported": "不支持",
  "Partially handled": "部分处理",
  "warn": "警告",
  "Scroll to latest entry": "滚动到最新条目",
  "Latest": "最新",

  // ── Misc tooltips ────────────────────────────────────────────────────────
  "Set Map Battleback": "设置地图战斗背景",
  "Fog changes require the MakerStudio plugin in-game": "迷雾更改需要游戏中的 MakerStudio 插件",
  "Targeting MakerStudio fog layers requires the MakerStudio plugin in-game": "针对 MakerStudio 迷雾图层需要游戏中的 MakerStudio 插件",
  "Loop the route from the top once it finishes.": "路线完成后从头循环。",
  "Skip a step instead of stalling when the target can't move.": "当目标无法移动时跳过一步而不是停滞。",
  "Open Game Simulator and run this route on the target event": "打开游戏模拟器并在目标事件上运行此路线",
  "Frame move-route commands require the MakerStudio plugin in-game": "帧移动路线命令需要游戏中的 MakerStudio 插件",
  "Remove from list": "从列表中移除",

  // ── Panel placeholders + canvas ──────────────────────────────────────────
  "Select a map from the tree to start editing": "从树中选择一个地图以开始编辑",
  "No map open": "没有打开的地图",
  "Mod panel is not available.": "模组面板不可用。",
  "Panel provided by mod {mod} — not loaded.": "由模组 {mod} 提供的面板——未加载。",
  "Error rendering panel \"{id}\": {error}": "渲染面板 \"{id}\" 时出错：{error}",
  "Layout uses panels from missing mods: {list}": "布局使用了缺失模组的面板：{list}",
  "No graphic selected.": "未选择图形。",
  "Loading map...": "正在加载地图…",
  "Button": "按钮",
  "Goods": "商品",
  "Label name cannot be empty.": "标签名称不能为空。",
  "Set Frame": "设置帧",
  "Edit Move Action": "编辑移动动作",

  // ── Visual move-route editor ──────────────────────────────────────────────
  "Visual Move Route Editor": "可视化移动路线编辑器",
  "Move Route Editor": "移动路线编辑器",
  "Step Up": "向上一步",
  "Step Down": "向下一步",
  "Step Left": "向左一步",
  "Step Right": "向右一步",
  "Undo Step": "撤销步骤",
  "Undo Step (alt)": "撤销步骤（替代）",
  "Redo Step": "重做步骤",
  "Draw path…": "绘制路径…",
  "Open the visual route editor: drag a path on the map to build the move sequence": "打开可视化路线编辑器：在地图上拖拽路径以构建移动序列",
  "The visual move-route editor writes steps as Maker Studio move-route commands — Makerstudio plugin required in-game": "可视化移动路线编辑器将步骤写为 Maker Studio 移动路线命令——需要游戏中的 Makerstudio 插件",
  "Maker Studio exclusive — the visual move-route editor replaces the stock Set Move Route command list with steps drawn on the map": "Maker Studio 专属——可视化移动路线编辑器用地图上绘制的步骤替换原始的设置移动路线命令列表",
  "Apply as Move Route": "应用为移动路线",
  "Set Start": "设置起点",
  "Tap to enable: next click sets the start cell": "点击以启用：下次点击设置起点格",
  "Undo last step": "撤销上一步",
  "Clear all steps": "清除所有步骤",
  "No steps yet — drag on the map to walk, or click far to jump.": "还没有步骤——在地图上拖拽以行走，或点击远处以跳跃。",
  "No map selected": "未选择地图",
  "Start": "起点",
  "Steps": "步骤",
  "Click a tile to set start": "点击图块以设置起点",
  "Drag to walk • click far to jump • {steps} walk • {turns} turn • {undo} undoes • {redo} redoes": "拖拽以行走 • 点击远处以跳跃 • {steps} 行走 • {turns} 转向 • {undo} 撤销 • {redo} 重做",
  "Drag to walk, click far to jump": "拖拽以行走，点击远处以跳跃",
  "Add Wait…": "添加等待…",
  "Add Wait": "添加等待",
  "Add a Wait with a frame count": "添加带有帧数的等待",
  "Walk": "行走",
  "Turn": "转向",
  "frames": "帧",
  "Double-click to edit frames": "双击以编辑帧",
  "Click a tile to rebase the Start cell": "点击图块以重新定位起点格",
  "20 frames = 1 second": "20 帧 = 1 秒",
  "No steps yet — drag on the map to walk, click far to jump, or use the Turn / Wait buttons above.": "还没有步骤——在地图上拖拽以行走，点击远处以跳跃，或使用上方的转向 / 等待按钮。",
  "{key}/{m}+drag or Shift+drag to pan • Ctrl+scroll to zoom • right-click undoes • tool changes what left-click does": "{key}/{m}+拖拽或 Shift+拖拽以平移 • Ctrl+滚动以缩放 • 右键撤销 • 工具改变左键的作用",
  "{key}/{m}+drag to pan • Ctrl+scroll to zoom • drag the map to walk • right-click to undo": "{key}/{m}+拖拽以平移 • Ctrl+滚动以缩放 • 拖拽地图以行走 • 右键撤销",
  "Click to select, Shift/Ctrl+click for more — right-click (or Undo) removes everything after the furthest one, Delete removes exactly the selected": "点击以选择，Shift/Ctrl+点击以选择更多——右键（或撤销）移除最远一个之后的所有内容，Delete 精确移除选中的内容",
  "Step {n} marked — right-click removes everything after it": "已标记步骤 {n}——右键移除它之后的所有内容",
  "{n} steps selected — Delete removes them": "已选择 {n} 个步骤——Delete 移除它们",
  "Delete selected steps": "删除选中的步骤",
  "Remove {n} steps?": "移除 {n} 个步骤？",
  "This removes everything after the marked step. This cannot be undone from this dialog, but Ctrl+Y restores it.": "这会移除标记步骤之后的所有内容。无法从此对话框撤销，但 Ctrl+Y 可以恢复。",
  "This removes the {n} selected steps. This cannot be undone from this dialog, but Ctrl+Y restores them.": "这会移除选中的 {n} 个步骤。无法从此对话框撤销，但 Ctrl+Y 可以恢复它们。",

  // ── Command param-form hints ─────────────────────────────────────────────
  "20 frames = 1 second.": "20 帧 = 1 秒。",
  "Stores the input button id in the chosen variable (Input::DOWN=2, LEFT=4, RIGHT=6, UP=8, A=11, B=12, C=13, X=14, Y=15, Z=16, L=17, R=18). Stores 0 if no key was pressed.": "将输入按钮 id 存储到所选变量中（Input::DOWN=2, LEFT=4, RIGHT=6, UP=8, A=11, B=12, C=13, X=14, Y=15, Z=16, L=17, R=18）。如果没有按下任何键，则存储 0。",
  "Event ID: -1 = Player, 0 = This Event, 1+ = events on this map.": "事件 ID：-1 = 玩家，0 = 此事件，1+ = 此地图上的事件。",
  "Branch runs when this item is in the inventory.": "此道具在背包中时运行分支。",
  "Branch runs when this weapon is in the inventory.": "此武器在背包中时运行分支。",
  "Branch runs when this armor is in the inventory.": "此防具在背包中时运行分支。",
  "Branch runs while this button is being pressed.": "按住此按钮时运行分支。",
  "Branch runs when this actor is in the party.": "此角色在队伍中时运行分支。",
  "Branch runs when this enemy has appeared in the troop.": "此敌人出现在敌群中时运行分支。",
  "No matching Label command on this page yet.": "此页上还没有匹配的标签命令。",
  "Stores number of this item in inventory.": "存储此道具在背包中的数量。",
  "Channels A–D match RMXP defaults; E–Z require runtime support.": "通道 A–D 匹配 RMXP 默认值；E–Z 需要运行时支持。",
  "Selecting a layer fills the fields below with its current properties. Edit them, then the command applies them to that layer in-game. (Use Change Fog Opacity for opacity.)": "选择图层会用其当前属性填充下面的字段。编辑它们，然后命令会在游戏中将它们应用到该图层。（不透明度请使用更改迷雾不透明度。）",
  "Empty = default fade. Files in Graphics/Transitions/.": "空 = 默认淡入淡出。文件位于 Graphics/Transitions/。",
  "Negative value = damage. Allow Knockout permits HP to drop to 0 mid-battle.": "负值 = 伤害。允许倒下允许 HP 在对战中降到 0。",
  "Drag rows to reorder, or use ▲/▼ buttons. Double-click a row with parameters to re-edit it. New commands insert after the selected row.": "拖拽行以重新排序，或使用 ▲/▼ 按钮。双击带参数的行以重新编辑。新命令插入到所选行之后。",
  "Drag rows to reorder, or use ▲/▼ buttons. Space/Enter or double-click edits a row. Ctrl+C/X/V copy/cut/paste, Ctrl+Z/Y undo/redo. New commands insert after the selection.": "拖拽行以重新排序，或使用 ▲/▼ 按钮。空格/回车或双击编辑一行。Ctrl+C/X/V 复制/剪切/粘贴，Ctrl+Z/Y 撤销/重做。新命令插入到选择之后。",
  "Drag to reorder, {undo}/{redo} undo/redo": "拖拽以重新排序，{undo}/{redo} 撤销/重做",
  "End of route": "路线结束",
  "Double-click to edit, drag to reorder": "双击以编辑，拖拽以重新排序",
  "Frame numbers are 1-based. Uncheck an axis to leave it unchanged. The grid size comes from the target's character-sheet columns/rows.": "帧编号从 1 开始。取消选中某个轴以保持不变。网格大小来自目标的角色工作表列/行。",

  // ── Welcome screen ───────────────────────────────────────────────────────
  "Open an existing game folder or pick from below.": "打开现有的游戏文件夹或从下方选择。",
  "Open Game Folder": "打开游戏文件夹",
  "Recent": "最近",
  "Most Used": "最常用",
  "No projects yet": "还没有项目",
  "{count} open": "{count} 次打开",
  "{count} opens": "{count} 次打开",

  // ── Project loading dialog ──────────────────────────────────────────────
  "Loading project…": "正在加载项目…",
  "Loading maps": "正在加载地图",
  "Loading tilesets": "正在加载图块集",
  "Loading system data": "正在加载系统数据",
  "Loading project data": "正在加载项目数据",
  "Opening map": "正在打开地图",
  "Loading tileset graphics": "正在加载图块集图形",

  // ── Custom Shape Brush (Brush Editor) ───────────────────────────────────────
  "Brush Editor": "画笔编辑器",
  "Brush Editor…": "画笔编辑器…",
  "Open the Custom Shape Brush editor": "打开自定义形状画笔编辑器",
  "Active custom brush": "活动自定义画笔",
  "Clear custom brush": "清除自定义画笔",
  "Switch to the default brush": "切换到默认画笔",
  "Switch to the custom brush": "切换到自定义画笔",
  "Shape": "形状",
  "Square": "方形",
  "Circle": "圆形",
  "Diamond": "菱形",
  "Plus": "十字",
  "Size:": "大小：",
  "Min size:": "最小大小：",
  "Max size:": "最大大小：",
  "Width:": "宽度：",
  "Height:": "高度：",
  "Toggle cell": "切换单元格",
  "Tiles": "图块",
  "No tiles in the pool — the brush paints the currently selected tile.": "未选中图块——画笔绘制当前选中的图块。",
  "Add fixed tile": "添加固定图块",
  "Add tiles…": "添加图块…",
  "Add Current Tile": "添加当前图块",
  "Add tiles": "添加图块",
  "Tileset:": "图块集：",
  "No tilesets": "没有图块集",
  "Add to pool": "添加到池",
  "No selection": "没有选择",
  "Single tile": "单个图块",
  "Group {w}×{h}": "组 {w}×{h}",
  "The pool already has a Current Tile entry": "已选择此图块",
  "Current Tile": "当前图块",
  "Relative weight": "相对权重",
  "Props": "属性",
  "Mode:": "模式：",
  "Shared": "共享",
  "Per-tile": "逐图块",
  "Select a tile in the pool to edit its properties.": "选择图块以编辑其属性。",
  "Priority:": "优先级：",
  "Terrain tag:": "地形标签：",
  "Passage:": "通行：",
  "Custom Brush Presets": "自定义画笔预设",
  "Brush Editor...": "画笔编辑器…",
  "Default (square)": "默认（方形）",
  "Custom (unsaved)": "自定义（未保存）",
  "Switch the active custom brush": "切换活动自定义画笔",
  "Shared Properties": "共享属性",
  "Per-tile Override": "逐图块覆盖",
  "Clear (follow shared)": "清除（跟随共享）",
  "This tile overrides the shared properties.": "此图块覆盖共享属性。",
  "This tile follows the shared properties — edit any value to override.": "此图块跟随共享属性——编辑任何值以覆盖。",
  "Click a tile to give it its own properties; click its image to swap it.": "点击图块赋予属性；点击其图像以替换它。",
  "Replace this tile": "替换此图块",
  "Has its own properties": "有自己的属性",
  "Replace tile": "替换图块",
  "Mask brushes are sized in the Brush Editor": "蒙版画笔在画笔编辑器中调整大小",
  "Advanced Conditions": "高级条件",
  "No advanced conditions. ANDed on top of the checks above.": "未设置高级条件；与上面的条件检查进行与运算。",
  "Match ALL of these": "匹配所有这些",
  "Match ANY of these": "匹配其中任意一个",
  "Empty OR is always false": "空的或组始终为假",
  "Group": "组",
  "AND": "与",
  "OR": "或",
  "Advanced conditions require the MakerStudio plugin in-game": "高级条件需要游戏中的 MakerStudio 插件",
  "Block requires the MakerStudio plugin in-game": "阻挡需要游戏中的 MakerStudio 插件",
  "{title}: {message}": "{title}：{message}",
  // ── Text codes ───────────────────────────────────────────────────────
  "Text codes": `文字代码`,
  "Hide text codes": `隐藏文字代码`,
  "Copied to clipboard — paste it in a Script command.": `已复制到剪贴板——请将其粘贴到脚本命令中。`,
  "Couldn't copy to clipboard — select and copy the text manually.": `无法复制到剪贴板——请选中并手动复制文本。`,
  "Substitution": `替代`,
  "Style": `风格`,
  "NameBox (LBDS only)": `名字框（仅限LBDS）`,
  "Value of game variable n.": `游戏变量n的值。`,
  "Player's name.": `玩家的名字。`,
  "Player's money, formatted with the currency symbol.": `玩家的零花钱，带有货币符号。`,
  "RPG Maker actor n's name.": `RPG Maker中角色n的名字。`,
  "Male text color.": `男性的文字颜色。`,
  "Female text color.": `女性的文字颜色。`,
  "Text color matching the player's gender.": `与玩家性别相符的文字颜色。`,
  "Text color for the opposite gender.": `与玩家性别相反的文字颜色。`,
  "Spanish gender vowel for agreement: o (male) / a (female).": `西班牙语中表示性别一致的元音：o（阳性）/ a（阴性）。`,
  'Like \\@, but empty instead of "o" for male.': `类似于\\@，但阳性时为空而非"o"。`,
  "Color n from the current windowskin's palette.": `从当前窗口皮肤的调色板中选择颜色 n。`,
  "RGBA color from an 8-digit hex code.": `根据8位十六进制代码获取RGBA颜色。`,
  "Sign-post box (expands to \\op\\cl\\ts[]\\w[texto]).": `路标窗口（\\op\\cl\\ts[]\\w[texto]的扩展）。`,
  "Literal backslash character.": `反斜杠符号。`,
  "Line break.": `换行。`,
  "Text color (RGB hex).": `文字颜色（RGB十六进制）。`,
  "Color with packed shadow (8 hex base + 8 hex shadow).": `带填充阴影的颜色（8位十六进制基色 + 8位十六进制阴影）。`,
  "Explicit base and shadow color (what \\b/\\r/\\c[n] generate).": `显式的基色和阴影色（即 \\b/\\r/\\c[n] 生成的颜色）。`,
  "Text opacity.": `文字透明度。`,
  "Bold.": `粗体。`,
  "Italic.": `斜体。`,
  "Underline.": `下划线。`,
  "Strikethrough.": `删除线。`,
  "Outline (style 1).": `描边（风格1）`,
  "Outline (style 2).": `描边（风格2）`,
  "Font size.": `字体大小`,
  "Font (falls back to Arial if it doesn't exist).": `字体（如果不存在则退回到Arial体）。`,
  "Align left.": `左对齐。`,
  "Align right.": `右对齐。`,
  "Align center.": `居中。`,
  "Short pause (0.25s).": `短暂停（0.25s）。`,
  "Pause (1s).": `暂停（1s）。`,
  "Wait for the player to press a button to continue.": `等待玩家按下按钮继续，`,
  "Continue without a final button-press prompt.": `无需最终按键确认提示，直接继续。`,
  "Wait n/20 seconds, with a pause prompt.": `等待n/20秒，有暂停提示。`,
  "Wait n/20 seconds, without a pause prompt.": `等待n/20秒，无暂停提示。`,
  "Change text speed for the rest of the message (n/80s per character).": `更改剩余信息的文字速度（每个字n/80秒）。`,
  "Play a sound effect (Audio/SE/...).": `播放音效（Audio/SE/...）。`,
  "Play a short music track (ME).": `播放短音频（ME）。`,
  "Change the message window's skin.": `更改消息框的皮肤。`,
  "Force the message window's line count to n.": `强制消息框的行数为n。`,
  "Animate the window sliding in.": `让窗口以滑入的效果出现。`,
  "Animate the window sliding out at the end (\\cl[sonido] also plays a sound).": `让窗口以滑出的效果消失（\\cl[sonido]会播放音效）。`,
  "Show a face picture from Graphics/Pictures.": `显示Graphics/Pictures中的面部贴图。`,
  "Show an RMVX-style face (96x96 tile, index 0-15) from Graphics/Faces.": `显示Graphics/Faces中的RMVX风格的面部贴图（96x96 像素，索引 0-15）。`,
  "Show the player's money window while the message lasts.": `信息持续时，显示玩家的零花钱窗口。`,
  "Show the player's coins window.": `显示玩家的零花钱窗口。`,
  "Show the Battle Points window.": `显示战斗点数窗口。`,
  "Move the message window to the top of the screen.": `将消息框移动到屏幕顶部。`,
  "Center the message window vertically.": `将消息框垂直居中。`,
  "Move the message window to the bottom (default).": `将消息框移动到底部（默认）。`,
  "Shout effect: shout windowskin, shout SE, window shakes in.": `喊叫效果：喊叫窗口皮肤，喊叫 SE，窗口震动着出现。`,
  "Inline choice list stored in a game variable.": `存储在游戏变量中的内联选项列表。`,
  "Show the player's name in the NameBox.": `在名字框里显示玩家的名字。`,
  "Show a fixed name in the NameBox.": `在名字框里显示固定的名字。`,
  "Show the name stored in game variable n.": `显示存储在游戏变量n中的名字。`,
  "Stop showing the NameBox.": `停止显示名字框。`

};
